/* eslint-disable import/prefer-default-export */
export enum EIconType { // 注意这里的 key 用于组件的对外 props，不要随意修改，且保持小写
  'alert' = 'e64b', // 警告 ⚠
  'alert-fill' = 'e604', // 警告（圆形填充）
  'angle-circle-right' = 'e60c', // 圈圈箭头 - 右
  'angle-down' = 'e65a', // 角箭头 - 下
  'angle-left' = 'e658', // 角箭头 - 左
  'angle-right' = 'e65e', // 角箭头 - 右
  'angle-up' = 'e660', // 角箭头 - 上
  'arrow-left' = 'e7c3', // 箭头 ← - 左
  'arrow-right' = 'e88c', // 箭头 → - 右
  'apps' = 'e60e', // 应用（负数）
  'app' = 'e603', // 应用（单个）
  'cart' = 'e882', // 购物车
  'check-circle-fill' = 'e7e2', // 勾（带填充圈）
  'copy' = 'e60d', // 复制
  'dingding' = 'e881', // 钉钉
  'drag' = 'e6e1', // 拖拽
  'empty' = 'e655', // 空
  'external' = 'e610', // 外部链接
  'face-cry' = 'e7f8', // 哭脸
  'face-smile' = 'e7f9', // 笑脸
  'filter' = 'e608', // 过滤
  'global' = 'e70d', // 全球 - 用于 @alicloud/console-base-wd-region
  'go-top' = 'e694', // 回到顶部
  'help' = 'e81f', // 帮助
  'lang' = 'e70b', // 语言
  'loading' = 'e602', // 加载中
  'logo-aliyun' = 'e605', // 【-】
  'logo-aliyun-word-cn' = 'e653', // 图标文字 - 「阿里云」
  'logo-aliyun-word-en' = 'e654', // 图标文字 - 「Alibaba Cloud」
  'menu-all' = 'e6e3', // 菜单（九宫格）
  'minus' = 'e768', // -
  'notice' = 'e887', // 通知（铃铛）
  'plus' = 'e659', // +
  'question-fill' = 'e726', // 问号（圆形填充）
  'recycle-bin' = 'e621', // 删除（垃圾桶）
  'refresh' = 'e6c1', // 刷新
  'pin' = 'e79e', // 固定
  'preference' = 'e6b5', // 偏好设置
  'search' = 'e82e', // 搜索
  'star-hollow' = 'e609', // 空心的星
  'star' = 'e611', // 星（收藏）
  'stick-right' = 'e657', // 面板 - 固定到右侧
  'terminal' = 'e866', // 终端
  'theme-light-dark' = 'e6aa', // 黑/白主题 转 180 度后
  'toolkit-api' = 'e740', // API Inspector
  'toolkit-contact' = 'e61f', // 联系我们
  'toolkit-advisory' = 'e656', // 智能在线
  'toolkit-feedback' = 'e666', // 反馈
  'toolkit-qr' = 'e640', // QR
  'toolkit-survey' = 'e606', // 问卷
  'toolkit-version-new' = 'e62e', // 尝试新版
  'toolkit-version-old' = 'e72f', // 返回旧版
  'triangle-down' = 'e719', // 实心小三角 - 下
  'triangle-left' = 'e60a', // 实心小三角 - 左
  'triangle-right' = 'e718', // 实心小三角 - 右
  'triangle-up' = 'e60b', // 实心小三角 - 上
  'user-ak' = 'e871', // 用户菜单栏 - AK（AccessKey）
  'user-ambassador' = 'e870', // 用户菜单栏 - 云大使（推荐返利后台）
  'user-auth' = 'e624', // 用户菜单栏 - 实名认证
  'user-club' = 'e861', // 用户菜单栏 - 会员积分
  'user-info' = 'e607', // 用户菜单栏 - 用户基本信息
  'user-security' = 'e668', // 用户菜单栏 - 安全信息管理
  'user-ram' = 'e862', // 用户菜单栏 - 访问控制（RAM）
  'user-rights' = 'e85d', // 用户菜单栏 - 会员权益
  'user-sc' = 'e777', // 用户菜单栏 - 安全控制（Security Control）
  'user-ss' = 'e600', // 用户菜单栏 - 安全设置（Security Settings）
  'x-circle-fill' = 'e601', // 删除（带填充圈 X）
  'x' = 'e61d' // 删除（X）
}
