/* eslint-disable @typescript-eslint/naming-convention */
export enum EIconType {
  _ = 'e600', // 兜底阿里云图标【-】
  acmp = 'e6d3', // 多云成本运营
  acms = 'e636', // 应用配置管理
  actiontrail = 'e710', // 操作审计
  adam = 'e79f', // 数据库和应用迁移
  addrp = 'e675', // 地址标准化
  ads = 'e731', // 分析型数据库 MySQL 版
  advisor = 'e616', // 智能顾问
  afs = 'e740', // 数据风控（业务安全）
  ahas = 'e8d0', // 应用高可用服务
  aiccs = 'e604', // 智能联络中心
  airec = 'e933', // 智能推荐
  alidfs = 'e8ef', // 文件存储 HDFS
  alikafka = 'e86c', // 消息队列 Kafka
  alimt = 'e8c3', // 机器翻译
  amqp = 'e910', // 消息队列 for AMQP
  antibot = 'e872', // 爬虫风险管理
  apigateway = 'e615', // API 网关
  aqs = 'e741', // 云安全中心（安骑士）
  arms = 'e638', // 应用实时监控服务
  avds = 'e848', // 网站威胁扫描（应用安全）
  baas = 'e885', // 区块链服务
  bastion = 'e73f', // 堡垒机（安全管理）
  batchcompute = 'e7b2', // 批量计算
  bccluster = 'e6d2', // 智能计算灵骏
  beebot = 'e7e0', // 云小蜜
  bpstudio = 'e68b', // 云架构设计工具 CADT
  brainindustrial = 'e792',
  cas = 'e744', // SSL 证书（应用安全）
  cassandra = 'e926', // 云数据库 Cassandra 版
  cbn = 'e8a5', // 云企业网
  ccc = 'e823', // 云呼叫中心
  cciot = 'e603', // 云连接器 CcIot
  ccs = 'e7d9', // 云客服
  cddc = 'e674', // 云数据库专属集群
  cdn = 'e738', // CDN
  cdt = 'e6d1', // 云数据传输
  cfw = 'e7a9', // 云防火墙
  clickhouse = 'e67f', // 云数据库 ClickHouse
  cloudap = 'e7d7', // 云 AP
  cloudauth = 'e831', // 实人认证
  cmn = 'e8f2', // 云网管
  cms = 'e8b5', // 云监控
  codepipeline = 'e78d', // CodePipeline
  companyreg = 'e91f', // 企业工商注册服务
  computenest = 'e61d', // 计算巢服务
  config = 'e92f', // 配置审计
  cos = 'e702', // 容器服务
  cps = 'e71d', // 移动推送
  cr = 'e84a', // 容器镜像服务
  csas = 'e685', // 云安全访问服务
  csb = 'e79c', // 云服务总线
  csk = 'e702', // 容器服务 Kubernetes 版
  cts = 'e891', // 内容安全（业务安全）
  cvc = 'e661', // 云视频会议
  databot = 'e6be', // 智能数据助理
  datahub = 'e759',
  datai = 'e754', // 数据集成
  dataphin = 'e860', // 智能数据构建与管理
  datav = 'e753', // DataV 数据可视化
  dbaudit = 'e742', // 数据库审计（数据安全）
  dbes = 'e91a', // 数据库专家服务
  dbfs = 'e6e5', // 数据库文件存储
  dbs = 'e7e3', // 数据库备份
  dcdn = 'e86a', // 全站加速
  ddh = 'e6e6', // 专有宿主机
  ddos = 'e87b', // DDoS 基础防护
  ddospro = 'e87c', // DDoS 高防
  dds = 'e625', // 云数据库 MongoDB 版
  developer = 'e8c2', // API Explorer
  dg = 'e920', // 数据库网关
  dide = 'e723', // DataWorks
  dlf = 'e686', // 数据湖构建
  dm = 'e71f', // 邮件推送
  dms = 'e62b', // 数据管理 DMS
  dns = 'e769', // 云解析 DNS
  domain = 'e766', // 域名
  drds = 'e623', // 分布式关系型数据库
  drp = 'e6de', // DataQuotient 画像分析
  dts = 'e62e', // 数据传输服务
  dycdp = 'e783', // 流量服务
  dyiot = 'e7a4', // 物联网无线连接服务
  dypls = 'e87e', // 号码隐私保护
  dypns = 'e8f6', // 号码认证服务
  dysms = 'e784', // 短信服务
  dytns = 'e6e8', // 号码百科
  dyvms = 'e782', // 语音服务
  eais = 'e68e', // 弹性加速计算实例
  ebs = 'e605', // 块存储 Elastic Block Storage
  eci = 'e8db', // 弹性容器实例
  ecs = 'e606', // 云服务器
  edas = 'e631', // 企业级分布式应用服务 EDAS
  eds = 'e7d2', // 弹性云桌面
  ehpc = 'e7b1', // 弹性高性能计算
  elasticsearch = 'e80f', // 阿里云 Elasticsearch
  emas = 'e607', // 移动研发平台
  emapreduce = 'e778', // E-MapReduce
  energyexpert = 'e8ff', // 能耗宝
  ens = 'e83a', // 边缘节点服务 ENS
  entconsole = 'e639', // 资源管理
  ess = 'e609', // 弹性伸缩
  eventbridge = 'e67a', // 消息事件总线
  ews = 'e767', // 弹性 Web 托管
  face = 'e8c5', // 人脸识别
  fc = 'e60c', // 函数计算
  feedback = 'e720', // 移动用户反馈
  fnf = 'e90f', // 函数工作流
  ga = 'e633', // 全球加速
  gameshield = 'e746', // 游戏盾
  gds = 'e902', // 图数据库 GDB
  gpdb = 'e6c3', // 云原生数据仓库 AnalyticDB PostgreSQL 版
  idrsservice = 'e6bd', // 智能双录质检
  igraph = 'e925', // 图计算服务 - Graph Compute Service
  imp = 'e6c1', // 低代码音视频工厂
  governance = 'e6b2', // 云治理中心
  grafana = 'ebb0', // Grafana 服务
  gts = 'e637', // 全局事务服务
  gws = 'e87d', // 图形工作站
  hbase = 'e78b', // 云数据库 HBase 版
  hbr = 'e619', // 混合云备份
  hcs_mgw = 'e630', // 闪电立方
  hdm = 'e840', // 混合云数据库管理 HDM
  hdr = 'e61a', // 混合云容灾
  hologram = 'e859', // 交互式分析
  holowatcher = 'e687', // 全息空间
  host = 'e76d', // 云虚拟主机
  hotfix = 'e722', // 移动热修复
  hsm = 'e747', // 加密服务（数据安全）
  httpdns = 'e76b', // HTTPDNS
  ice = 'e602', // 智能媒体生产
  idaas = 'e601', // 应用身份服务
  indvi = 'e664', // 工业视觉智能
  image = 'e8c6', // 图像识别
  imagesearch = 'e8c7', // 图像搜索
  imm = 'e8bb', // 智能媒体管理
  iot = 'e916', // 物联网平台
  iotid = 'e8f8', // IoT 设备身份认证
  iotedge = 'e945', // 物联网边缘计算
  iovcc = 'e881', // 智联车管理云平台
  ip = 'e611', // 弹性公网 IP
  ipv6trans = 'e882', // IPv6 转换服务
  iqa = 'e932', // 智能问答
  isoc = 'e677', // IoT 安全运营中心
  ivision = 'e8d3', // 智能视觉（模型训练预测）
  kms = 'e716', // 密钥管理服务
  kvstore = 'e624', // 云数据库 Redis 版
  lc = 'e921', // 逻辑编排
  lindorm = 'e7fa', // 云原生多模数据库 Lindorm
  linkedmall = 'e8fd', // Linkedmall 企业商城国际
  linkwan = 'e8eb', // 物联网络管理平台
  live = 'e63d', // 视频直播
  mail = 'e76c', // 企业邮箱
  man = 'e8a2', // 移动数据分析
  market = 'e69a', // 云市场
  memcache = 'e627', // 云数据库 Memcache 版
  miniappdev = 'e91b', // 小程序云
  mns = 'e634', // 消息服务
  mqc = 'e8a1', // 移动测试
  mq4iot = 'e912', // 微消息队列 for MQTT
  mse = 'e922', // 微服务引擎
  mss = 'e779', // 安全管家（安全服务）
  mts = 'e777', // 媒体处理
  multimediaai = 'e934', // 多媒体 AI
  nas = 'e617', // 文件存储 NAS
  nat_gw = 'e612', // NAT 网关
  nlp = 'e8cb', // 自然语言处理
  nls = 'e8cd', // 智能语音交互
  npp = 'e8a3', // Node.js 性能平台
  oce = 'e739', // 云数据库 OceanBase
  ocr = 'e8ce', // 文字识别
  odps = 'e75d', // MaxCompute
  ons = 'e632', // 消息队列 RocketMQ
  oos = 'e659', // 运维编排
  openanalytics = 'e874', // Data Lake Analytics
  opensearch = 'e72b', // 开放搜索
  oss = 'e774', // 对象存储 OSS
  ots = 'e642', // 表格存储
  outboundbot = 'e6bc', // 智能外呼机器人
  pai = 'e8c8', // 机器学习 PAI
  pcdn = 'e794', // PCDN
  petadata = 'e73b', // 云数据库 HybridDB for MySQL
  polardb = 'e7b5', // 云数据库 POLARDB
  privatelink = 'e626', // 私网连接
  privatezone = 'e6f4', // 云解析 PrivateZone
  prometheus = 'e689', // Prometheus 监控服务
  pts = 'e635', // 性能测试服务
  quickbi = 'e757', // Quick BI
  ram = 'e74a', // 访问控制
  rdc = 'e699', // 云效 DevOps
  yunxiao = 'e699', // 云效
  rds = 'e73a', // 云数据库 RDS 版
  retailir = 'e960', // 货架商品识别与管理
  expressconnect = 'e614', // 高速通道
  ros = 'e60a', // 资源编排
  rsimganalys = 'e930', // 卫星及无人机遥感影像分析产品
  rtc = 'e86b', // 音视频通信 RTC
  sae = 'e914', // 轻量级分布式应用服务
  saf = 'e879', // 风险识别（业务安全）
  sas = 'e749', // 云安全中心（态势感知）
  sca = 'e729', // 智能对话分析
  scdn = 'e628', // 安全加速 SCDN
  schedulerx = 'e71a', // 分布式调度平台 SchedulerX
  sddp = 'e64c', // 敏感数据保护
  servicemesh = 'e666', // 服务网格
  sgw = 'e61b', // 云存储网关
  slb = 'e610', // 负载均衡
  sls = 'e72a', // 日志服务
  smartag = 'e8b3', // 智能接入网关
  smc = 'e918', // 服务器迁移中心
  snsu = 'e887', // 云通信网络加速
  spark = 'e679', // 数据洞察
  flowbag = 'e613', // 共享流量包
  stream = 'e72c', // 实时计算
  swas = 'e7b4', // 轻量应用服务器
  tair = 'e676', // 云原生内存数据库 Tair
  trademark = 'e8c1', // 商标服务
  tsdb = 'e785', // 时序时空数据库 TSDB
  uis = 'e919', // 极致互联网服务
  vcs = 'e68c', // 视觉计算服务 Visual Compute Service
  vod = 'e63e', // 视频点播
  vpc = 'e60f', // 专有网络 VPC
  vpn = 'e7f9', // VPN 网关
  vs = 'e90a', // 视频监控
  waf = 'e74f', // Web 应用防火墙（网络安全）
  webx = 'e915', // Web 应用托管服务（Web+）
  xtrace = 'e8d1', // 链路追踪
  xz = 'e721', // 先知（安全服务）
  yida = 'e90c', // 宜搭
  yundun = 'e74d' // 云盾
}
