export const MESSAGE_TYPE_MICRO_BROWSER_PORTAL_CREATED = 'app_2_console_base:micro_browser_portal/created';
export const MESSAGE_TYPE_MICRO_BROWSER_PORTAL_REMOVED = 'app_2_console_base:micro_browser_portal/removed';
export const MESSAGE_TYPE_MICRO_BROWSER_PORTAL_TOGGLE_VISIBLE = 'app_2_console_base:micro_browser_portal/toggle_visible';