import {
  IThemeColors
} from '../types';
import {
  COLOR_BRAND_ALIYUN,
  COLOR_WHITE,
  COLOR_BLACK,
  COLOR_TRANSPARENT,
  COLOR_GRAY_LIGHTER,
  COLOR_GRAY_LIGHT,
  COLOR_GRAY,
  COLOR_GRAY_DARK,
  COLOR_GRAY_DARKER,
  COLOR_RED_LIGHTER,
  COLOR_RED_LIGHT,
  COLOR_RED,
  COLOR_RED_DARK,
  COLOR_RED_DARKER,
  COLOR_GREEN_LIGHTER,
  COLOR_GREEN_LIGHT,
  COLOR_GREEN,
  COLOR_GREEN_DARK,
  COLOR_GREEN_DARKER,
  COLOR_BLUE_LIGHTER,
  COLOR_BLUE_LIGHT,
  COLOR_BLUE,
  COLOR_BLUE_DARK,
  COLOR_BLUE_DARKER,
  COLOR_ORANGE_LIGHTER,
  COLOR_ORANGE_LIGHT,
  COLOR_ORANGE,
  COLOR_ORANGE_DARK,
  COLOR_ORANGE_DARKER
} from '../color';

const COLOR = {
  BRAND_ALIYUN: COLOR_BRAND_ALIYUN,
  
  TEXT_ACCENT: COLOR_BLUE,
  
  TEXT_ERROR: COLOR_RED, // 错误
  TEXT_WARN: COLOR_ORANGE, // 警告
  TEXT_EMPHASIS: '#ff6a00', // 突出说明，如「金额」、「最重要链接」等
  TEXT_INFO: COLOR_BLUE, // 重要提示
  TEXT_POSITIVE: COLOR_GREEN, // 积极和正面引导的文本，如「验证通过」、「已支付」等
  
  TEXT_TITLE: COLOR_GRAY_DARKER, // 标题
  TEXT_PRIMARY: COLOR_GRAY_DARK, // 主要文字
  TEXT_SECONDARY: COLOR_GRAY, // 次要文字
  TEXT_CAPTION: COLOR_GRAY_LIGHT, // 说明文字
  TEXT_DISABLED: COLOR_GRAY_LIGHTER, // Disabled 状态文字
  
  LINK: COLOR_BLUE,
  LINK_GRAY: COLOR_GRAY, // 次要链接
  
  LINE_LIGHT: '#efefef', // 浅色分割线
  LINE: '#dedede', // 默认分割线、组件边框
  LINE_DARK: '#737373', // 深色分割线、组件边框 Hover 效果
  
  FILL_LIGHTER: '#fafafa',
  FILL_LIGHT: '#f7f7f7',
  FILL: '#f5f5f5',
  FILL_DARK: '#ebebeb',
  FILL_DARKER: '#dedede',
  
  SUCCESS_LIGHTER: COLOR_GREEN_LIGHTER,
  SUCCESS_LIGHT: COLOR_GREEN_LIGHT,
  SUCCESS: COLOR_GREEN,
  SUCCESS_DARK: COLOR_GREEN_DARK,
  SUCCESS_DARKER: COLOR_GREEN_DARKER,
  
  WARN_LIGHTER: COLOR_ORANGE_LIGHTER,
  WARN_LIGHT: COLOR_ORANGE_LIGHT,
  WARN: COLOR_ORANGE,
  WARN_DARK: COLOR_ORANGE_DARK,
  WARN_DARKER: COLOR_ORANGE_DARKER,
  
  ERROR_LIGHTER: COLOR_RED_LIGHTER,
  ERROR_LIGHT: COLOR_RED_LIGHT,
  ERROR: COLOR_RED,
  ERROR_DARK: COLOR_RED_DARK,
  ERROR_DARKER: COLOR_RED_DARKER,
  
  INFO_LIGHTER: COLOR_BLUE_LIGHTER,
  INFO_LIGHT: COLOR_BLUE_LIGHT,
  INFO: COLOR_BLUE,
  INFO_DARK: COLOR_BLUE_DARK,
  INFO_DARKER: COLOR_BLUE_DARKER,
  
  HELP: COLOR_GRAY,
  HELP_DARK: COLOR_GRAY_DARK,
  HELP_LIGHT: COLOR_GRAY_LIGHT
};

export default COLOR;
