import {
  IColorText,
  IColorEssential
} from '../types';

export default function createConstColorBaseText(E: IColorEssential): IColorText {
  return {
    TEXT_TRANSPARENT: E.TRANSPARENT,
    TEXT_WHITE: E.WHITE,
    TEXT_BLACK: E.BLACK,
    TEXT_INVERSE: E.INVERSE,
    TEXT_BRAND: E.BRAND,
    TEXT_BRAND_HOVER: E.BRAND_HOVER,
    TEXT_BRAND_ACTIVE: E.BRAND_ACTIVE,
    TEXT_ACCENT: E.ACCENT,
    TEXT_ACCENT_HOVER: E.ACCENT_HOVER,
    TEXT_ACCENT_ACTIVE: E.ACCENT_ACTIVE,
    TEXT_PRIMARY: E.GRAY_PRIMARY,
    TEXT_SECONDARY: E.GRAY_SECONDARY,
    TEXT_TERTIARY: E.GRAY_TERTIARY,
    TEXT_DISABLED: E.GRAY_DISABLED,
    TEXT_HELP: E.HELP,
    TEXT_INFO: E.INFO,
    TEXT_SUCCESS: E.SUCCESS,
    TEXT_WARNING: E.WARNING,
    TEXT_ERROR: E.ERROR,
    TEXT_DANGER: E.DANGER,
    TEXT_EMPHASIS: E.EMPHASIS,
    TEXT_CODE: E.CODE
  };
}
