import {
  IColorEssential,
  IColorBg
} from '../types';

export default function createConstColorBaseBg(E: IColorEssential): IColorBg {
  return {
    BG_TRANSPARENT: E.TRANSPARENT,
    BG_WHITE: E.WHITE,
    BG_BLACK: E.BLACK,
    BG_INVERSE: E.INVERSE_BG,
    BG_BRAND: E.BRAND,
    BG_BRAND_HOVER: E.BRAND_HOVER,
    BG_BRAND_ACTIVE: E.BRAND_ACTIVE,
    BG_ACCENT: E.ACCENT,
    BG_ACCENT_HOVER: E.ACCENT_HOVER,
    BG_ACCENT_ACTIVE: E.ACCENT_ACTIVE,
    BG_PRIMARY: E.GRAY_PRIMARY_BG,
    BG_SECONDARY: E.GRAY_SECONDARY_BG,
    BG_SECONDARY_FADE: E.GRAY_SECONDARY_FADE_BG,
    BG_TERTIARY: E.GRAY_TERTIARY_BG,
    BG_TERTIARY_FADE: E.GRAY_TERTIARY_FADE_BG,
    BG_DISABLED: E.GRAY_DISABLED,
    BG_HELP: E.HELP,
    BG_HELP_TINT: E.HELP_TINT,
    BG_HELP_TINT_FADE: E.HELP_TINT_FADE,
    BG_INFO: E.INFO,
    BG_INFO_TINT: E.INFO_TINT,
    BG_INFO_TINT_FADE: E.INFO_TINT_FADE,
    BG_SUCCESS: E.SUCCESS,
    BG_SUCCESS_TINT: E.SUCCESS_TINT,
    BG_SUCCESS_TINT_FADE: E.SUCCESS_TINT_FADE,
    BG_WARNING: E.WARNING,
    BG_WARNING_TINT: E.WARNING_TINT,
    BG_WARNING_TINT_FADE: E.WARNING_TINT_FADE,
    BG_ERROR: E.ERROR,
    BG_ERROR_TINT: E.ERROR_TINT,
    BG_ERROR_TINT_FADE: E.ERROR_TINT_FADE,
    BG_DANGER: E.DANGER,
    BG_BACKDROP: E.BACKDROP
  };
}
