import {
  IColorText,
  IColorBg,
  IColorBorder,
  IColorButton
} from '../types';

/**
 * 按钮，需要定义
 * * 文字色
 * * 背景色
 * * 边框色
 * 
 * 每种色需要定义如下状态：
 * * 正常
 * * `:hover` + `:focus`
 * * `:active`
 * * `:disabled`
 */
export default function createConstColorButton(FG: IColorText, BG: IColorBg, BD: IColorBorder): IColorButton {
  return {
    /**
     * 菜单栏一整条的按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字2 | 透明浅灰底 | 无边
     * HOVER | 黑字2 | 透明浅灰底 | 无边
     * ACTIVE | 黑字2 | 透明浅灰底 | 无边
     * 禁用 | 灰字 | 无底 | 灰边
     */
    BUTTON_MENU_TEXT: FG.TEXT_SECONDARY,
    BUTTON_MENU_BG: BG.BG_TRANSPARENT,
    BUTTON_MENU_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_MENU_TEXT_HOVER: FG.TEXT_SECONDARY,
    BUTTON_MENU_BG_HOVER: BG.BG_SECONDARY,
    BUTTON_MENU_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_MENU_TEXT_ACTIVE: FG.TEXT_SECONDARY,
    BUTTON_MENU_BG_ACTIVE: BG.BG_SECONDARY,
    BUTTON_MENU_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_MENU_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_MENU_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_MENU_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 危险警告按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 白字 | 红底 | 红边
     * HOVER | 白字 | 红底 | 红边
     * ACTIVE | 白字 | 深红底 | 红边
     * 禁用 | 白字 | 灰底 | 灰边
     */
    BUTTON_DANGER_TEXT: FG.TEXT_WHITE,
    BUTTON_DANGER_BG: BG.BG_DANGER,
    BUTTON_DANGER_BORDER: BD.BORDER_DANGER,
    BUTTON_DANGER_TEXT_HOVER: FG.TEXT_WHITE,
    BUTTON_DANGER_BG_HOVER: BG.BG_DANGER,
    BUTTON_DANGER_BORDER_HOVER: BD.BORDER_DANGER,
    BUTTON_DANGER_TEXT_ACTIVE: FG.TEXT_WHITE,
    BUTTON_DANGER_BG_ACTIVE: BG.BG_DANGER,
    BUTTON_DANGER_BORDER_ACTIVE: BD.BORDER_DANGER,
    BUTTON_DANGER_TEXT_DISABLED: FG.TEXT_WHITE,
    BUTTON_DANGER_BG_DISABLED: BG.BG_DISABLED,
    BUTTON_DANGER_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 主按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 白字 | 蓝底 | 蓝边
     * HOVER | 白字 | 蓝底 | 蓝边
     * 禁用 | 白字 | 灰底 | 灰边
     */
    BUTTON_PRIMARY_TEXT: FG.TEXT_WHITE,
    BUTTON_PRIMARY_BG: BG.BG_ACCENT,
    BUTTON_PRIMARY_BORDER: BD.BORDER_ACCENT,
    BUTTON_PRIMARY_TEXT_HOVER: FG.TEXT_WHITE,
    BUTTON_PRIMARY_BG_HOVER: BG.BG_ACCENT_HOVER,
    BUTTON_PRIMARY_BORDER_HOVER: BD.BORDER_ACCENT_HOVER,
    BUTTON_PRIMARY_TEXT_ACTIVE: FG.TEXT_WHITE,
    BUTTON_PRIMARY_BG_ACTIVE: BG.BG_ACCENT_ACTIVE,
    BUTTON_PRIMARY_BORDER_ACTIVE: BD.BORDER_ACCENT_ACTIVE,
    BUTTON_PRIMARY_TEXT_DISABLED: FG.TEXT_WHITE,
    BUTTON_PRIMARY_BG_DISABLED: BG.BG_DISABLED,
    BUTTON_PRIMARY_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 次按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 白底 | 灰边
     * HOVER | 黑字 | 浅灰底 | 灰边
     * 禁用 | 灰字 | 浅灰底 | 灰边
     */
    BUTTON_SECONDARY_TEXT: FG.TEXT_SECONDARY,
    BUTTON_SECONDARY_BG: BG.BG_SECONDARY,
    BUTTON_SECONDARY_BORDER: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_TEXT_HOVER: FG.TEXT_PRIMARY,
    BUTTON_SECONDARY_BG_HOVER: BG.BG_PRIMARY,
    BUTTON_SECONDARY_BORDER_HOVER: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_TEXT_ACTIVE: FG.TEXT_PRIMARY,
    BUTTON_SECONDARY_BG_ACTIVE: BG.BG_PRIMARY,
    BUTTON_SECONDARY_BORDER_ACTIVE: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_SECONDARY_BG_DISABLED: BG.BG_SECONDARY,
    BUTTON_SECONDARY_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 次按钮 Alt - 空心
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 白底 | 灰边
     * HOVER | 黑字 | 浅灰底 | 灰边
     * 禁用 | 灰字 | 浅灰底 | 灰边
     */
    BUTTON_SECONDARY_ALT_TEXT: FG.TEXT_SECONDARY,
    BUTTON_SECONDARY_ALT_BG: BG.BG_TRANSPARENT,
    BUTTON_SECONDARY_ALT_BORDER: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_ALT_TEXT_HOVER: FG.TEXT_PRIMARY,
    BUTTON_SECONDARY_ALT_BG_HOVER: BG.BG_SECONDARY,
    BUTTON_SECONDARY_ALT_BORDER_HOVER: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_ALT_TEXT_ACTIVE: FG.TEXT_PRIMARY,
    BUTTON_SECONDARY_ALT_BG_ACTIVE: BG.BG_SECONDARY,
    BUTTON_SECONDARY_ALT_BORDER_ACTIVE: BD.BORDER_SECONDARY,
    BUTTON_SECONDARY_ALT_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_SECONDARY_ALT_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_SECONDARY_ALT_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 三级按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 黑字 | 灰底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TERTIARY_TEXT: FG.TEXT_SECONDARY,
    BUTTON_TERTIARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TERTIARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_HOVER: FG.TEXT_PRIMARY,
    BUTTON_TERTIARY_BG_HOVER: BG.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_ACTIVE: FG.TEXT_PRIMARY,
    BUTTON_TERTIARY_BG_ACTIVE: BG.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TERTIARY_BG_DISABLED: BG.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 三级按钮 Alt
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 灰底 | 无边
     * HOVER | 黑字 | 灰底+ | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TERTIARY_ALT_TEXT: FG.TEXT_SECONDARY,
    BUTTON_TERTIARY_ALT_BG: BG.BG_SECONDARY,
    BUTTON_TERTIARY_ALT_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_ALT_TEXT_HOVER: FG.TEXT_PRIMARY,
    BUTTON_TERTIARY_ALT_BG_HOVER: BG.BG_TERTIARY,
    BUTTON_TERTIARY_ALT_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_ALT_TEXT_ACTIVE: FG.TEXT_PRIMARY,
    BUTTON_TERTIARY_ALT_BG_ACTIVE: BG.BG_TERTIARY,
    BUTTON_TERTIARY_ALT_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_ALT_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TERTIARY_ALT_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TERTIARY_ALT_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 主 Brand 按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 白字 | 橙底 | 橙边
     * HOVER | 白字 | 橙底 | 橙边
     * 禁用 | 白字 | 灰底 | 灰边
     */
    BUTTON_BRAND_PRIMARY_TEXT: FG.TEXT_WHITE,
    BUTTON_BRAND_PRIMARY_BG: BG.BG_BRAND,
    BUTTON_BRAND_PRIMARY_BORDER: BD.BORDER_BRAND,
    BUTTON_BRAND_PRIMARY_TEXT_HOVER: FG.TEXT_WHITE,
    BUTTON_BRAND_PRIMARY_BG_HOVER: BG.BG_BRAND_HOVER,
    BUTTON_BRAND_PRIMARY_BORDER_HOVER: BD.BORDER_BRAND_HOVER,
    BUTTON_BRAND_PRIMARY_TEXT_ACTIVE: FG.TEXT_WHITE,
    BUTTON_BRAND_PRIMARY_BG_ACTIVE: BG.BG_BRAND_ACTIVE,
    BUTTON_BRAND_PRIMARY_BORDER_ACTIVE: BD.BORDER_BRAND_ACTIVE,
    BUTTON_BRAND_PRIMARY_TEXT_DISABLED: FG.TEXT_WHITE,
    BUTTON_BRAND_PRIMARY_BG_DISABLED: BG.BG_DISABLED,
    BUTTON_BRAND_PRIMARY_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 次 Brand 按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 橙字 | 无底 | 橙边
     * HOVER | 橙字 | 浅底 | 橙边
     * 禁用 | 灰字 | 浅底 | 灰边
     */
    BUTTON_BRAND_SECONDARY_TEXT: FG.TEXT_BRAND,
    BUTTON_BRAND_SECONDARY_BG: BG.BG_PRIMARY,
    BUTTON_BRAND_SECONDARY_BORDER: BD.BORDER_BRAND,
    BUTTON_BRAND_SECONDARY_TEXT_HOVER: BD.BORDER_BRAND_HOVER,
    BUTTON_BRAND_SECONDARY_BG_HOVER: BG.BG_PRIMARY,
    BUTTON_BRAND_SECONDARY_BORDER_HOVER: BD.BORDER_BRAND_HOVER,
    BUTTON_BRAND_SECONDARY_TEXT_ACTIVE: FG.TEXT_BRAND_ACTIVE,
    BUTTON_BRAND_SECONDARY_BG_ACTIVE: BG.BG_PRIMARY,
    BUTTON_BRAND_SECONDARY_BORDER_ACTIVE: BD.BORDER_BRAND_ACTIVE,
    BUTTON_BRAND_SECONDARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_BRAND_SECONDARY_BG_DISABLED: BG.BG_PRIMARY,
    BUTTON_BRAND_SECONDARY_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 次 Brand 按钮 Alt - 空心
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 橙字 | 无底 | 橙边
     * HOVER | 橙字 | 浅底 | 橙边
     * 禁用 | 灰字 | 浅底 | 灰边
     */
    BUTTON_BRAND_SECONDARY_ALT_TEXT: FG.TEXT_BRAND,
    BUTTON_BRAND_SECONDARY_ALT_BG: BG.BG_TRANSPARENT,
    BUTTON_BRAND_SECONDARY_ALT_BORDER: BD.BORDER_BRAND,
    BUTTON_BRAND_SECONDARY_ALT_TEXT_HOVER: BD.BORDER_BRAND_HOVER,
    BUTTON_BRAND_SECONDARY_ALT_BG_HOVER: BG.BG_SECONDARY,
    BUTTON_BRAND_SECONDARY_ALT_BORDER_HOVER: BD.BORDER_BRAND_HOVER,
    BUTTON_BRAND_SECONDARY_ALT_TEXT_ACTIVE: FG.TEXT_BRAND_ACTIVE,
    BUTTON_BRAND_SECONDARY_ALT_BG_ACTIVE: BG.BG_SECONDARY,
    BUTTON_BRAND_SECONDARY_ALT_BORDER_ACTIVE: BD.BORDER_BRAND_ACTIVE,
    BUTTON_BRAND_SECONDARY_ALT_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_BRAND_SECONDARY_ALT_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_BRAND_SECONDARY_ALT_BORDER_DISABLED: BD.BORDER_DISABLED,
    
    /**
     * 三级按钮（Brand 变种）
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 橙字 | 无底 | 无边
     * HOVER | 橙字 | 灰底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_BRAND_TERTIARY_TEXT: FG.TEXT_BRAND,
    BUTTON_BRAND_TERTIARY_BG: BG.BG_TRANSPARENT,
    BUTTON_BRAND_TERTIARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_BRAND_TERTIARY_TEXT_HOVER: FG.TEXT_BRAND_HOVER,
    BUTTON_BRAND_TERTIARY_BG_HOVER: BG.BG_SECONDARY,
    BUTTON_BRAND_TERTIARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_BRAND_TERTIARY_TEXT_ACTIVE: FG.TEXT_BRAND_ACTIVE,
    BUTTON_BRAND_TERTIARY_BG_ACTIVE: BG.BG_SECONDARY,
    BUTTON_BRAND_TERTIARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_BRAND_TERTIARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_BRAND_TERTIARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_BRAND_TERTIARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 主文字按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 蓝字 | 无底 | 无边
     * HOVER | 蓝字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_PRIMARY_TEXT: FG.TEXT_ACCENT,
    BUTTON_TEXT_PRIMARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_TEXT_HOVER: FG.TEXT_ACCENT_HOVER,
    BUTTON_TEXT_PRIMARY_BG_HOVER: BG.BG_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_TEXT_ACTIVE: FG.TEXT_ACCENT_HOVER,
    BUTTON_TEXT_PRIMARY_BG_ACTIVE: BG.BG_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TEXT_PRIMARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TEXT_PRIMARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 次文字按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 蓝字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_SECONDARY_TEXT: FG.TEXT_SECONDARY,
    BUTTON_TEXT_SECONDARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_TEXT_HOVER: FG.TEXT_ACCENT,
    BUTTON_TEXT_SECONDARY_BG_HOVER: BG.BG_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_TEXT_ACTIVE: FG.TEXT_ACCENT,
    BUTTON_TEXT_SECONDARY_BG_ACTIVE: BG.BG_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TEXT_SECONDARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TEXT_SECONDARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 三级文字按钮
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 黑字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_TERTIARY_TEXT: FG.TEXT_SECONDARY,
    BUTTON_TEXT_TERTIARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_TEXT_HOVER: FG.TEXT_PRIMARY,
    BUTTON_TEXT_TERTIARY_BG_HOVER: BG.BG_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_TEXT_ACTIVE: FG.TEXT_PRIMARY,
    BUTTON_TEXT_TERTIARY_BG_ACTIVE: BG.BG_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TEXT_TERTIARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TEXT_TERTIARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 主文字按钮（Brand 变种）
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 橙字 | 无底 | 无边
     * HOVER | 橙字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_BRAND_PRIMARY_TEXT: FG.TEXT_BRAND,
    BUTTON_TEXT_BRAND_PRIMARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_TEXT_HOVER: FG.TEXT_BRAND_HOVER,
    BUTTON_TEXT_BRAND_PRIMARY_BG_HOVER: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_TEXT_ACTIVE: FG.TEXT_BRAND_HOVER,
    BUTTON_TEXT_BRAND_PRIMARY_BG_ACTIVE: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TEXT_BRAND_PRIMARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_PRIMARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT,
    
    /**
     * 次文字按钮（Brand 变种）
     * 
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 橙字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_BRAND_SECONDARY_TEXT: FG.TEXT_SECONDARY,
    BUTTON_TEXT_BRAND_SECONDARY_BG: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_BORDER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_TEXT_HOVER: FG.TEXT_BRAND,
    BUTTON_TEXT_BRAND_SECONDARY_BG_HOVER: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_BORDER_HOVER: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_TEXT_ACTIVE: FG.TEXT_BRAND,
    BUTTON_TEXT_BRAND_SECONDARY_BG_ACTIVE: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_BORDER_ACTIVE: BD.BORDER_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_TEXT_DISABLED: FG.TEXT_DISABLED,
    BUTTON_TEXT_BRAND_SECONDARY_BG_DISABLED: BG.BG_TRANSPARENT,
    BUTTON_TEXT_BRAND_SECONDARY_BORDER_DISABLED: BD.BORDER_TRANSPARENT
  };
}
