import {
  IColorInput,
  IColorText,
  IColorBg,
  IColorBorder
} from '../types';

export default function createConstColorInput(FG: IColorText, BG: IColorBg, BD: IColorBorder): IColorInput {
  return {
    INPUT_TEXT: FG.TEXT_SECONDARY,
    INPUT_BG: BG.BG_PRIMARY,
    INPUT_BORDER: BD.BORDER_TERTIARY,
    INPUT_TEXT_HOVER: FG.TEXT_SECONDARY,
    INPUT_BG_HOVER: BG.BG_PRIMARY,
    INPUT_BORDER_HOVER: BD.BORDER_SECONDARY,
    INPUT_TEXT_FOCUS: FG.TEXT_SECONDARY,
    INPUT_BG_FOCUS: BG.BG_PRIMARY,
    INPUT_BORDER_FOCUS: BD.BORDER_ACCENT,
    INPUT_BORDER_FOCUS_BRAND: BD.BORDER_BRAND,
    INPUT_TEXT_DISABLED: FG.TEXT_DISABLED,
    INPUT_BG_DISABLED: BG.BG_SECONDARY,
    INPUT_BORDER_DISABLED: BD.BORDER_DISABLED,
    INPUT_PLACEHOLDER: FG.TEXT_TERTIARY
  };
}
