import {
  IColorEssential,
  IColorBorder
} from '../types';

export default function createConstColorBaseBorder(E: IColorEssential): IColorBorder {
  return {
    BORDER_TRANSPARENT: E.TRANSPARENT,
    BORDER_WHITE: E.WHITE,
    BORDER_BRAND: E.BRAND,
    BORDER_BRAND_HOVER: E.BRAND_HOVER,
    BORDER_BRAND_ACTIVE: E.BRAND_ACTIVE,
    BORDER_ACCENT: E.ACCENT,
    BORDER_ACCENT_HOVER: E.ACCENT_HOVER,
    BORDER_ACCENT_ACTIVE: E.ACCENT_ACTIVE,
    BORDER_PRIMARY: E.GRAY_PRIMARY_BD,
    BORDER_SECONDARY: E.GRAY_SECONDARY_BD,
    BORDER_TERTIARY: E.GRAY_TERTIARY_BD,
    BORDER_DISABLED: E.GRAY_DISABLED,
    BORDER_HELP: E.HELP,
    BORDER_INFO: E.INFO,
    BORDER_SUCCESS: E.SUCCESS,
    BORDER_WARNING: E.WARNING,
    BORDER_ERROR: E.ERROR,
    BORDER_DANGER: E.DANGER
  };
}
