upgrade: true
dep: dev,prod
format: group
reject:
- '@types/react'
- '@types/react-dom'
- '@simplewebauthn/*' # TODO 升级 4 → 5
- 'codemirror' # TODO 升级 5 → 6
- 'react' # 先不升级 18
- 'react-dom' # 先不升级 18
- 'stylelint' # 14 不行
- 'stylelint-config-standard'
- 'stylelint-order'
- 'unfetch' # 5.0 输出的是 .mjs 对构建有要求...
- 'typescript' # 5.0.2 在 WebStorm 的时候 react 类型无法解析
