echo @alicloud/console-base-error-prompt-proxy@1.4.5-alpha.2 && git tag -d @alicloud/console-base-error-prompt-proxy@1.4.5-alpha.2
echo @alicloud/console-base-global@1.1.66-alpha.2 && git tag -d @alicloud/console-base-global@1.1.66-alpha.2
echo @alicloud/console-base-log-sls@1.2.1-alpha.2 && git tag -d @alicloud/console-base-log-sls@1.2.1-alpha.2
echo @alicloud/console-base-messenger@1.3.57-alpha.2 && git tag -d @alicloud/console-base-messenger@1.3.57-alpha.2
echo @alicloud/console-fetcher-basic@1.5.31-alpha.2 && git tag -d @alicloud/console-fetcher-basic@1.5.31-alpha.2
echo @alicloud/console-fetcher-interceptor-arms@1.1.53-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-arms@1.1.53-alpha.2
echo @alicloud/console-fetcher-interceptor-fecs@1.1.63-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-fecs@1.1.63-alpha.2
echo @alicloud/console-fetcher-interceptor-req-mock@1.1.59-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-req-mock@1.1.59-alpha.2
echo @alicloud/console-fetcher-interceptor-req-security@1.1.53-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-req-security@1.1.53-alpha.2
echo @alicloud/console-fetcher-interceptor-res-biz@1.1.53-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-res-biz@1.1.53-alpha.2
echo @alicloud/console-fetcher-interceptor-res-error-message@1.1.55-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-res-error-message@1.1.55-alpha.2
echo @alicloud/console-fetcher-interceptor-res-risk@1.1.81-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-res-risk@1.1.81-alpha.2
echo @alicloud/console-fetcher-interceptor-sls@1.1.62-alpha.2 && git tag -d @alicloud/console-fetcher-interceptor-sls@1.1.62-alpha.2
echo @alicloud/console-fetcher-proxy@1.4.45-alpha.2 && git tag -d @alicloud/console-fetcher-proxy@1.4.45-alpha.2
echo @alicloud/console-fetcher@1.5.42-alpha.2 && git tag -d @alicloud/console-fetcher@1.5.42-alpha.2
echo @alicloud/console-logger-sls@1.2.1-alpha.2 && git tag -d @alicloud/console-logger-sls@1.2.1-alpha.2
echo @alicloud/fetcher-demo-helpers@1.1.50-alpha.2 && git tag -d @alicloud/fetcher-demo-helpers@1.1.50-alpha.2
echo @alicloud/fetcher-fetch@1.2.50-alpha.2 && git tag -d @alicloud/fetcher-fetch@1.2.50-alpha.2
echo @alicloud/fetcher-interceptor-cache-local@1.1.27-alpha.2 && git tag -d @alicloud/fetcher-interceptor-cache-local@1.1.27-alpha.2
echo @alicloud/fetcher-interceptor-merger@1.0.43-alpha.2 && git tag -d @alicloud/fetcher-interceptor-merger@1.0.43-alpha.2
echo @alicloud/fetcher-jsonp@1.1.51-alpha.2 && git tag -d @alicloud/fetcher-jsonp@1.1.51-alpha.2
echo @alicloud/fetcher@1.1.53-alpha.2 && git tag -d @alicloud/fetcher@1.1.53-alpha.2
echo @alicloud/logger-sls@1.5.1-alpha.2 && git tag -d @alicloud/logger-sls@1.5.1-alpha.2
echo @alicloud/u2f-api@0.0.1-alpha.2 && git tag -d @alicloud/u2f-api@0.0.1-alpha.2