export const PRODUCT_MAPPING: Record<string, string> = {
  acmp: '多云成本运营',
  acms: '应用配置管理',
  actiontrail: '操作审计',
  acvs: 'VMware 服务',
  adam: '数据库和应用迁移 ADAM',
  adcp: '分布式云容器平台',
  addrp: '地址标准化',
  adp: '云原生应用交付平台',
  ads: '云原生数据仓库 ADB MySQL 版',
  advisor: '智能顾问',
  afs: '验证码',
  ahas: '应用高可用服务',
  aiccs: '智能联络中心',
  airec: '智能推荐 AIRec',
  alibababcp: '多端电商商城',
  alidfs: '文件存储 HDFS',
  alikafka: '消息队列 Kafka 版',
  alime: '客服工作台',
  alimt: '机器翻译',
  aliyunape: '数字地球引擎',
  amqp: '消息队列 RabbitMQ 版',
  antcloudauth: '金融级实人认证',
  antibot: '爬虫风险管理',
  antppc: '蚂蚁隐私计算服务平台',
  apds: '云迁移中心',
  apigateway: 'API 网关',
  appstreaming: '无影云应用',
  aqs: '云安全中心（安骑士）',
  arms: '应用实时监控服务 ARMS',
  ask: 'Serverless 容器服务 ASK',
  assettech: '云行情',
  avatar: '虚拟数字人',
  avds: '漏洞扫描（应用安全）',
  baas: '区块链服务',
  bastion: '堡垒机（安全运维）',
  'bastionhost-pam': '特权访问管理中心',
  batchcompute: '批量计算',
  bccluster: '智能计算灵骏',
  beebot: '智能对话机器人（云小蜜）',
  bigdatacst: '大数据专家服务',
  bizworks: 'BizWorks',
  bpstudio: '云速搭 CADT',
  braincitypa: '城市大脑·公共安全',
  brainindustrial: '工业大脑',
  bsn: 'ICP 备案',
  campuslink: '智能题库生产平台',
  cams: 'ChatAPP 消息服务',
  cas: 'SSL 证书（应用安全）',
  cassandra: '云数据库 Cassandra 版',
  cbn: '云企业网',
  cbwp: '共享带宽',
  ccc: '云呼叫中心',
  cciot: '云连接器',
  ccp: '内容协作平台',
  ccs: '客服工作台',
  cddc: '云数据库专属集群 MyBase',
  cdn: 'CDN',
  cdt: '云数据传输',
  cfw: '云防火墙（网络安全）',
  class: '互动课堂',
  clickhouse: '云数据库 ClickHouse',
  cloudap: '云 AP',
  cloudauth: '实人认证',
  cloudauthst: '智能核身',
  cloudera: 'CDP 企业数据云',
  cloudesl: '云价签',
  cloudgame: '云游戏平台',
  cloudinfo: '信息核验',
  cloudphone: '弹性云手机',
  cloudsso: '云 SSO',
  cmn: '云网管',
  cms: '云监控',
  codepipeline: 'CodePipeline',
  codestore: '机器人流程自动化',
  companyreg: '工商财税',
  computenest: '计算巢服务',
  config: '配置审计',
  cos: '容器服务',
  cps: '移动推送',
  cr: '容器镜像服务',
  csas: '办公安全平台 SASE',
  csb: '云服务总线 CSB',
  csb2: '微服务 API 网关',
  csk: '容器服务 Kubernetes 版',
  cts: '内容安全',
  cvc: '云会议',
  databot: '智能数据助理',
  datahub: '数据总线 DataHub',
  datai: '数据集成 Data Integration',
  dataphin: '智能数据构建与管理 Dataphin',
  datav: '数据可视化 DataV',
  dbaudit: '数据库审计',
  dbes: '数据库专家服务',
  dbfs: '数据库文件存储 DBFS',
  dbs: '数据库备份 DBS',
  dcdn: '全站加速',
  ddh: '专有宿主机',
  ddos: '流量安全（DDoS 基础防护）',
  ddospro: 'DDoS 高防',
  dds: '云数据库 MongoDB 版',
  developer: 'API 控制台',
  dg: '数据库网关 DG',
  diagnostic: 'ROS 诊断服务',
  dide: '大数据开发治理平台 DataWorks',
  dlf: '数据湖构建 DLF',
  dm: '邮件推送',
  dms: '数据管理 DMS',
  dns: '云解析 DNS',
  docmind: '文档智能',
  domain: '域名',
  drds: '云原生分布式数据库 PolarDB-X',
  drp: '数据资源平台',
  dtplus_overview: '数加控制台概览',
  dts: '数据传输服务 DTS',
  dycdp: '流量服务',
  dyiot: '物联网无线连接服务',
  dypls: '号码隐私保护',
  dypns: '号码认证服务',
  dysms: '短信服务',
  dytns: '号码百科',
  dyvms: '语音服务',
  eais: '弹性加速计算实例',
  eas: '弹性算法服务',
  ebs: '块存储 EBS',
  eci: '弹性容器实例 ECI',
  ecs: '云服务器 ECS',
  edas: '企业级分布式应用服务 EDAS',
  eds: '无影云桌面',
  eduplatform: '智慧教育平台',
  ehpc: '弹性高性能计算',
  elasticsearch: 'Elasticsearch',
  emapreduce: '开源大数据平台 E-MapReduce',
  emas: '移动研发平台 EMAS',
  energyexpert: '能耗宝',
  ens: '边缘节点服务 ENS',
  entconsole: '资源管理',
  ess: '弹性伸缩',
  eventbridge: '事件总线 EventBridge',
  ews: '弹性 Web 托管',
  expressconnect: '高速通道',
  face: '人脸识别',
  fc: '函数计算 FC',
  feedback: '移动用户反馈',
  finsmtengine: '金融智能引擎',
  flowbag: '共享流量包',
  fnf: 'Serverless 工作流',
  ga: '全球加速',
  gameshield: '游戏盾',
  gds: '图数据库 GDB',
  gemp: '运维事件中心',
  genomics: '基因分析平台',
  governance: '云治理中心',
  gpdb: '云原生数据仓库 ADB PostgreSQL 版',
  grace: '应用问题诊断分析平台',
  grafana: 'Grafana 服务',
  gts: '全局事务服务 GTS',
  gws: '云桌面',
  hbase: '云数据库 HBase 版',
  hbr: '混合云备份 HBR',
  hcs_mgw: '闪电立方 DataTransport',
  hdm: '数据库自治服务 DAS',
  hdr: '混合云容灾 HDR',
  hgw: '混合云存储',
  hologram: '实时数仓 Hologres',
  holowatcher: '全息空间',
  home: '控制台首页',
  host: '云虚拟主机',
  hotfix: '移动热修复',
  hsm: '加密服务',
  httpdns: 'HTTPDNS',
  iac: 'IaC 服务',
  iadoris: '交互式分析 Doris',
  ice: '智能媒体服务',
  idaas: '应用身份服务（IDaaS）',
  idrsservice: '智能双录质检',
  igraph: '图计算服务 Graph Compute',
  image: '图像识别',
  imagedetect: '图像检测',
  imagesearch: '图像搜索',
  imm: '智能媒体管理 IMM',
  imp: '低代码音视频工厂',
  indvi: '智能工业·工业视觉智能',
  iot: '物联网平台',
  iotedge: '物联网边缘计算',
  iotid: '物联网设备身份认证',
  iovcc: '智联车管理云平台',
  ip: '弹性公网 IP',
  ipa: '网络性能分析器',
  ipv6trans: 'IPv6 转换服务',
  iqa: '智能语义理解',
  irs: 'IP 资源服务',
  isoc: '物联网安全运营中心',
  ivision: '智能视觉（模型训练预测）',
  kms: '密钥管理服务',
  kvstore: '云数据库 Redis 版',
  lc: '逻辑编排',
  ledgerdb: '可信账本数据库',
  lindorm: '云原生多模数据库 Lindorm',
  linkedmall: 'Linkedmall 企业商城国际',
  linkwan: '物联网络管理平台',
  live: '视频直播',
  mail: '企业邮箱',
  man: '移动数据分析',
  market: '云市场',
  memcache: '云数据库 Memcache 版',
  miniappdev: '小程序云',
  mns: '消息服务 MNS',
  mpaas: '移动开发平台 mPaaS',
  mq4iot: '微消息队列 MQTT 版',
  mqc: '移动测试',
  mse: '微服务引擎',
  mss: '安全管家',
  mts: '媒体处理',
  multimediaai: '多媒体 AI',
  naam: '网络分析与监控',
  nas: '文件存储 NAS',
  nat_gw: 'NAT 网关',
  nis: '网络智能服务',
  nlp: '自然语言处理',
  nls: '智能语音交互',
  npp: 'Node.js 性能平台',
  oce: '云数据库 OceanBase',
  ocr: '文字识别',
  odps: '云原生大数据计算服务 MaxCompute',
  ons: '消息队列 RocketMQ 版',
  oos: '运维编排服务',
  openanalytics: '云原生数据湖分析',
  opensearch: '智能开放搜索 OpenSearch',
  opensearchoffice: '开放搜索内网版',
  opt: '优化求解器',
  oss: '对象存储 OSS',
  ots: '表格存储 TableStore',
  outboundbot: '智能外呼机器人',
  pai: '机器学习平台 PAI',
  pcdn: 'P2P 内容分发网络',
  pds: '网盘与相册服务 PDS',
  petadata: '云数据库 HybridDB for MySQL',
  polardb: '云数据库 PolarDB',
  premiumpics: '图片与设计',
  privatelink: '私网连接',
  privatezone: '云解析 PrivateZone',
  prometheus: 'Prometheus 监控服务',
  prophet: '公众趋势分析',
  pts: '性能测试服务',
  qcs: '量子计算模拟平台',
  ques: '文曲星教育平台',
  quickbi: '数据可视化分析 QuickBI',
  quicktracking: '全域采集与增长分析 QuickTracking',
  quotas: '配额中心',
  ram: '访问控制',
  rdc: '云效 DevOps',
  rds: '云数据库 RDS 版',
  renew: '续费管理',
  retailadvqa: '智能用户增长 QuickAudience',
  retailir: '货架商品识别与管理',
  ros: '资源编排',
  rsimganalys: '卫星及无人机遥感影像分析产品',
  rtc: '音视频通信 RTC',
  sae: 'Serverless 应用引擎 SAE',
  saf: '风险识别',
  salesforce: 'Salesforce',
  sas: '云安全中心（态势感知）',
  sasti: '威胁情报',
  sca: '智能对话分析',
  scdn: '安全加速 SCDN',
  schedulerx: '分布式任务调度 SchedulerX',
  sddp: '数据安全中心',
  servicecatalog: '服务目录',
  servicemesh: '服务网格',
  sgw: '云存储网关 CSG',
  slb: '负载均衡',
  sls: '日志服务 SLS',
  smartag: '智能接入网关',
  smc: '服务器迁移中心 SMC',
  snsu: '边缘网络加速 ENA',
  sofa: '金融分布式架构 SOFAStack',
  spark: '数据洞察 Databricks',
  spc: '支持与服务',
  stp: '共享流量包',
  stream: '实时计算 Flink 版',
  swas: '轻量应用服务器',
  swcopyright: '版权与专利服务',
  tair: '云原生内存数据库 Tair',
  tdsr: '三维空间重建',
  teambition: 'Teambition',
  trademark: '商标服务',
  tsdb: '时序数据库 TSDB',
  uem: '终端访问控制系统',
  uis: '5G高速上云服务',
  usercenter: '费用中心',
  vcs: '视觉计算服务',
  vision: '视觉智能开放平台',
  vod: '视频点播',
  vpc: '专有网络 VPC',
  vpn: 'VPN 网关',
  vs: '视图计算',
  waf: 'Web 应用防火墙（应用安全）',
  webx: 'Web 应用托管服务（Web+）',
  work: '工具与解决方案中心',
  xgip: '5G 互联平台',
  xtrace: '链路追踪',
  xz: '先知',
  yida: '宜搭',
  yuanjing: '元境',
  yundun: '云盾',
  yunxiao: '云效'
};
