// generated by generate-code-mixin-border.ts

import {
  css
} from 'styled-components';

import {
  COLOR
} from '../var';

export const mixinBorderTransparentColor = css`
  border-color: ${COLOR.BORDER_TRANSPARENT};
  border-color: var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderTransparent = css`
  border: 1px solid ${COLOR.BORDER_TRANSPARENT};
  border: 1px solid var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderTransparentTop = css`
  border-top: 1px solid ${COLOR.BORDER_TRANSPARENT};
  border-top: 1px solid var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderTransparentRight = css`
  border-right: 1px solid ${COLOR.BORDER_TRANSPARENT};
  border-right: 1px solid var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderTransparentBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_TRANSPARENT};
  border-bottom: 1px solid var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderTransparentLeft = css`
  border-left: 1px solid ${COLOR.BORDER_TRANSPARENT};
  border-left: 1px solid var(--cb-color-border-transparent, ${COLOR.BORDER_TRANSPARENT});
`;
export const mixinBorderWhiteColor = css`
  border-color: ${COLOR.BORDER_WHITE};
  border-color: var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderWhite = css`
  border: 1px solid ${COLOR.BORDER_WHITE};
  border: 1px solid var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderWhiteTop = css`
  border-top: 1px solid ${COLOR.BORDER_WHITE};
  border-top: 1px solid var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderWhiteRight = css`
  border-right: 1px solid ${COLOR.BORDER_WHITE};
  border-right: 1px solid var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderWhiteBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_WHITE};
  border-bottom: 1px solid var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderWhiteLeft = css`
  border-left: 1px solid ${COLOR.BORDER_WHITE};
  border-left: 1px solid var(--cb-color-border-white, ${COLOR.BORDER_WHITE});
`;
export const mixinBorderBrandColor = css`
  border-color: ${COLOR.BORDER_BRAND};
  border-color: var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrand = css`
  border: 1px solid ${COLOR.BORDER_BRAND};
  border: 1px solid var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrandTop = css`
  border-top: 1px solid ${COLOR.BORDER_BRAND};
  border-top: 1px solid var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrandRight = css`
  border-right: 1px solid ${COLOR.BORDER_BRAND};
  border-right: 1px solid var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrandBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_BRAND};
  border-bottom: 1px solid var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrandLeft = css`
  border-left: 1px solid ${COLOR.BORDER_BRAND};
  border-left: 1px solid var(--cb-color-border-brand, ${COLOR.BORDER_BRAND});
`;
export const mixinBorderBrandHoverColor = css`
  border-color: ${COLOR.BORDER_BRAND_HOVER};
  border-color: var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandHover = css`
  border: 1px solid ${COLOR.BORDER_BRAND_HOVER};
  border: 1px solid var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandHoverTop = css`
  border-top: 1px solid ${COLOR.BORDER_BRAND_HOVER};
  border-top: 1px solid var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandHoverRight = css`
  border-right: 1px solid ${COLOR.BORDER_BRAND_HOVER};
  border-right: 1px solid var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandHoverBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_BRAND_HOVER};
  border-bottom: 1px solid var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandHoverLeft = css`
  border-left: 1px solid ${COLOR.BORDER_BRAND_HOVER};
  border-left: 1px solid var(--cb-color-border-brand-hover, ${COLOR.BORDER_BRAND_HOVER});
`;
export const mixinBorderBrandActiveColor = css`
  border-color: ${COLOR.BORDER_BRAND_ACTIVE};
  border-color: var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderBrandActive = css`
  border: 1px solid ${COLOR.BORDER_BRAND_ACTIVE};
  border: 1px solid var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderBrandActiveTop = css`
  border-top: 1px solid ${COLOR.BORDER_BRAND_ACTIVE};
  border-top: 1px solid var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderBrandActiveRight = css`
  border-right: 1px solid ${COLOR.BORDER_BRAND_ACTIVE};
  border-right: 1px solid var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderBrandActiveBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_BRAND_ACTIVE};
  border-bottom: 1px solid var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderBrandActiveLeft = css`
  border-left: 1px solid ${COLOR.BORDER_BRAND_ACTIVE};
  border-left: 1px solid var(--cb-color-border-brand-active, ${COLOR.BORDER_BRAND_ACTIVE});
`;
export const mixinBorderAccentColor = css`
  border-color: ${COLOR.BORDER_ACCENT};
  border-color: var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccent = css`
  border: 1px solid ${COLOR.BORDER_ACCENT};
  border: 1px solid var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccentTop = css`
  border-top: 1px solid ${COLOR.BORDER_ACCENT};
  border-top: 1px solid var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccentRight = css`
  border-right: 1px solid ${COLOR.BORDER_ACCENT};
  border-right: 1px solid var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccentBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_ACCENT};
  border-bottom: 1px solid var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccentLeft = css`
  border-left: 1px solid ${COLOR.BORDER_ACCENT};
  border-left: 1px solid var(--cb-color-border-accent, ${COLOR.BORDER_ACCENT});
`;
export const mixinBorderAccentHoverColor = css`
  border-color: ${COLOR.BORDER_ACCENT_HOVER};
  border-color: var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentHover = css`
  border: 1px solid ${COLOR.BORDER_ACCENT_HOVER};
  border: 1px solid var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentHoverTop = css`
  border-top: 1px solid ${COLOR.BORDER_ACCENT_HOVER};
  border-top: 1px solid var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentHoverRight = css`
  border-right: 1px solid ${COLOR.BORDER_ACCENT_HOVER};
  border-right: 1px solid var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentHoverBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_ACCENT_HOVER};
  border-bottom: 1px solid var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentHoverLeft = css`
  border-left: 1px solid ${COLOR.BORDER_ACCENT_HOVER};
  border-left: 1px solid var(--cb-color-border-accent-hover, ${COLOR.BORDER_ACCENT_HOVER});
`;
export const mixinBorderAccentActiveColor = css`
  border-color: ${COLOR.BORDER_ACCENT_ACTIVE};
  border-color: var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderAccentActive = css`
  border: 1px solid ${COLOR.BORDER_ACCENT_ACTIVE};
  border: 1px solid var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderAccentActiveTop = css`
  border-top: 1px solid ${COLOR.BORDER_ACCENT_ACTIVE};
  border-top: 1px solid var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderAccentActiveRight = css`
  border-right: 1px solid ${COLOR.BORDER_ACCENT_ACTIVE};
  border-right: 1px solid var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderAccentActiveBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_ACCENT_ACTIVE};
  border-bottom: 1px solid var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderAccentActiveLeft = css`
  border-left: 1px solid ${COLOR.BORDER_ACCENT_ACTIVE};
  border-left: 1px solid var(--cb-color-border-accent-active, ${COLOR.BORDER_ACCENT_ACTIVE});
`;
export const mixinBorderPrimaryColor = css`
  border-color: ${COLOR.BORDER_PRIMARY};
  border-color: var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderPrimary = css`
  border: 1px solid ${COLOR.BORDER_PRIMARY};
  border: 1px solid var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderPrimaryTop = css`
  border-top: 1px solid ${COLOR.BORDER_PRIMARY};
  border-top: 1px solid var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderPrimaryRight = css`
  border-right: 1px solid ${COLOR.BORDER_PRIMARY};
  border-right: 1px solid var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderPrimaryBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_PRIMARY};
  border-bottom: 1px solid var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderPrimaryLeft = css`
  border-left: 1px solid ${COLOR.BORDER_PRIMARY};
  border-left: 1px solid var(--cb-color-border-primary, ${COLOR.BORDER_PRIMARY});
`;
export const mixinBorderSecondaryColor = css`
  border-color: ${COLOR.BORDER_SECONDARY};
  border-color: var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderSecondary = css`
  border: 1px solid ${COLOR.BORDER_SECONDARY};
  border: 1px solid var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderSecondaryTop = css`
  border-top: 1px solid ${COLOR.BORDER_SECONDARY};
  border-top: 1px solid var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderSecondaryRight = css`
  border-right: 1px solid ${COLOR.BORDER_SECONDARY};
  border-right: 1px solid var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderSecondaryBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_SECONDARY};
  border-bottom: 1px solid var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderSecondaryLeft = css`
  border-left: 1px solid ${COLOR.BORDER_SECONDARY};
  border-left: 1px solid var(--cb-color-border-secondary, ${COLOR.BORDER_SECONDARY});
`;
export const mixinBorderTertiaryColor = css`
  border-color: ${COLOR.BORDER_TERTIARY};
  border-color: var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderTertiary = css`
  border: 1px solid ${COLOR.BORDER_TERTIARY};
  border: 1px solid var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderTertiaryTop = css`
  border-top: 1px solid ${COLOR.BORDER_TERTIARY};
  border-top: 1px solid var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderTertiaryRight = css`
  border-right: 1px solid ${COLOR.BORDER_TERTIARY};
  border-right: 1px solid var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderTertiaryBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_TERTIARY};
  border-bottom: 1px solid var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderTertiaryLeft = css`
  border-left: 1px solid ${COLOR.BORDER_TERTIARY};
  border-left: 1px solid var(--cb-color-border-tertiary, ${COLOR.BORDER_TERTIARY});
`;
export const mixinBorderDisabledColor = css`
  border-color: ${COLOR.BORDER_DISABLED};
  border-color: var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderDisabled = css`
  border: 1px solid ${COLOR.BORDER_DISABLED};
  border: 1px solid var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderDisabledTop = css`
  border-top: 1px solid ${COLOR.BORDER_DISABLED};
  border-top: 1px solid var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderDisabledRight = css`
  border-right: 1px solid ${COLOR.BORDER_DISABLED};
  border-right: 1px solid var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderDisabledBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_DISABLED};
  border-bottom: 1px solid var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderDisabledLeft = css`
  border-left: 1px solid ${COLOR.BORDER_DISABLED};
  border-left: 1px solid var(--cb-color-border-disabled, ${COLOR.BORDER_DISABLED});
`;
export const mixinBorderHelpColor = css`
  border-color: ${COLOR.BORDER_HELP};
  border-color: var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderHelp = css`
  border: 1px solid ${COLOR.BORDER_HELP};
  border: 1px solid var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderHelpTop = css`
  border-top: 1px solid ${COLOR.BORDER_HELP};
  border-top: 1px solid var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderHelpRight = css`
  border-right: 1px solid ${COLOR.BORDER_HELP};
  border-right: 1px solid var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderHelpBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_HELP};
  border-bottom: 1px solid var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderHelpLeft = css`
  border-left: 1px solid ${COLOR.BORDER_HELP};
  border-left: 1px solid var(--cb-color-border-help, ${COLOR.BORDER_HELP});
`;
export const mixinBorderInfoColor = css`
  border-color: ${COLOR.BORDER_INFO};
  border-color: var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderInfo = css`
  border: 1px solid ${COLOR.BORDER_INFO};
  border: 1px solid var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderInfoTop = css`
  border-top: 1px solid ${COLOR.BORDER_INFO};
  border-top: 1px solid var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderInfoRight = css`
  border-right: 1px solid ${COLOR.BORDER_INFO};
  border-right: 1px solid var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderInfoBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_INFO};
  border-bottom: 1px solid var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderInfoLeft = css`
  border-left: 1px solid ${COLOR.BORDER_INFO};
  border-left: 1px solid var(--cb-color-border-info, ${COLOR.BORDER_INFO});
`;
export const mixinBorderSuccessColor = css`
  border-color: ${COLOR.BORDER_SUCCESS};
  border-color: var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderSuccess = css`
  border: 1px solid ${COLOR.BORDER_SUCCESS};
  border: 1px solid var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderSuccessTop = css`
  border-top: 1px solid ${COLOR.BORDER_SUCCESS};
  border-top: 1px solid var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderSuccessRight = css`
  border-right: 1px solid ${COLOR.BORDER_SUCCESS};
  border-right: 1px solid var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderSuccessBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_SUCCESS};
  border-bottom: 1px solid var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderSuccessLeft = css`
  border-left: 1px solid ${COLOR.BORDER_SUCCESS};
  border-left: 1px solid var(--cb-color-border-success, ${COLOR.BORDER_SUCCESS});
`;
export const mixinBorderWarningColor = css`
  border-color: ${COLOR.BORDER_WARNING};
  border-color: var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderWarning = css`
  border: 1px solid ${COLOR.BORDER_WARNING};
  border: 1px solid var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderWarningTop = css`
  border-top: 1px solid ${COLOR.BORDER_WARNING};
  border-top: 1px solid var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderWarningRight = css`
  border-right: 1px solid ${COLOR.BORDER_WARNING};
  border-right: 1px solid var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderWarningBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_WARNING};
  border-bottom: 1px solid var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderWarningLeft = css`
  border-left: 1px solid ${COLOR.BORDER_WARNING};
  border-left: 1px solid var(--cb-color-border-warning, ${COLOR.BORDER_WARNING});
`;
export const mixinBorderErrorColor = css`
  border-color: ${COLOR.BORDER_ERROR};
  border-color: var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderError = css`
  border: 1px solid ${COLOR.BORDER_ERROR};
  border: 1px solid var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderErrorTop = css`
  border-top: 1px solid ${COLOR.BORDER_ERROR};
  border-top: 1px solid var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderErrorRight = css`
  border-right: 1px solid ${COLOR.BORDER_ERROR};
  border-right: 1px solid var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderErrorBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_ERROR};
  border-bottom: 1px solid var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderErrorLeft = css`
  border-left: 1px solid ${COLOR.BORDER_ERROR};
  border-left: 1px solid var(--cb-color-border-error, ${COLOR.BORDER_ERROR});
`;
export const mixinBorderDangerColor = css`
  border-color: ${COLOR.BORDER_DANGER};
  border-color: var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
export const mixinBorderDanger = css`
  border: 1px solid ${COLOR.BORDER_DANGER};
  border: 1px solid var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
export const mixinBorderDangerTop = css`
  border-top: 1px solid ${COLOR.BORDER_DANGER};
  border-top: 1px solid var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
export const mixinBorderDangerRight = css`
  border-right: 1px solid ${COLOR.BORDER_DANGER};
  border-right: 1px solid var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
export const mixinBorderDangerBottom = css`
  border-bottom: 1px solid ${COLOR.BORDER_DANGER};
  border-bottom: 1px solid var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
export const mixinBorderDangerLeft = css`
  border-left: 1px solid ${COLOR.BORDER_DANGER};
  border-left: 1px solid var(--cb-color-border-danger, ${COLOR.BORDER_DANGER});
`;
