export const HEIGHT_FORM_CONTROL = 32;
export const PADDING_FORM_CONTROL_HORIZONTAL = 12;

export const HEIGHT_INPUT_SWITCH = 18;
export const WIDTH_INPUT_SWITCH = HEIGHT_INPUT_SWITCH * 2 - 4;
export const SPACING_INPUT_SWITCH_INNER = 2;
export const SIZE_INPUT_SWITCH_KNOB = HEIGHT_INPUT_SWITCH - SPACING_INPUT_SWITCH_INNER * 2;
