import {
  IThemeColors
} from '../types';
import {
  COLOR_BRAND_ALIYUN,
  COLOR_EMPHASIS,
  COLOR_WHITE,
  COLOR_BLACK,
  COLOR_TRANSPARENT,
  COLOR_TEXT_LIGHTER,
  COLOR_TEXT_LIGHT,
  COLOR_TEXT,
  COLOR_TEXT_DARK,
  COLOR_TEXT_DARKER,
  COLOR_LINE_LIGHTER,
  COLOR_LINE_LIGHT,
  COLOR_LINE,
  COLOR_LINE_DARK,
  COLOR_LINE_DARKER,
  COLOR_FILL_LIGHTER,
  COLOR_FILL_LIGHT,
  COLOR_FILL,
  COLOR_FILL_DARK,
  COLOR_FILL_DARKER,
  COLOR_INFO_LIGHTER,
  COLOR_INFO_LIGHT,
  COLOR_INFO,
  COLOR_INFO_DARK,
  COLOR_INFO_DARKER,
  COLOR_SUCCESS_LIGHTER,
  COLOR_SUCCESS_LIGHT,
  COLOR_SUCCESS,
  COLOR_SUCCESS_DARK,
  COLOR_SUCCESS_DARKER,
  COLOR_WARN_LIGHTER,
  COLOR_WARN_LIGHT,
  COLOR_WARN,
  COLOR_WARN_DARK,
  COLOR_WARN_DARKER,
  COLOR_ERROR_LIGHTER,
  COLOR_ERROR_LIGHT,
  COLOR_ERROR,
  COLOR_ERROR_DARK,
  COLOR_ERROR_DARKER
} from '../color';

const COLOR: IThemeColors = {
  WHITE: COLOR_WHITE,
  BLACK: COLOR_BLACK,
  TRANSPARENT: COLOR_TRANSPARENT,
  BRAND_ALIYUN: COLOR_BRAND_ALIYUN,
  LINK: COLOR_INFO,
  LINK_GRAY: COLOR_TEXT_DARK, // 次要链接
  
  TEXT_ERROR: COLOR_ERROR, // 错误
  TEXT_WARN: COLOR_WARN, // 警告
  TEXT_EMPHASIS: COLOR_EMPHASIS, // 突出说明，如「金额」、「最重要链接」等
  TEXT_INFO: COLOR_INFO, // 重要提示
  TEXT_POSITIVE: COLOR_SUCCESS, // 积极和正面引导的文本，如「验证通过」、「已支付」等
  
  TEXT_DISABLED: COLOR_TEXT_LIGHTER,
  TEXT_CAPTION: COLOR_TEXT_LIGHT,
  TEXT_SECONDARY: COLOR_TEXT,
  TEXT_PRIMARY: COLOR_TEXT_DARK,
  TEXT_TITLE: COLOR_TEXT_DARKER,
  
  LINE_LIGHTER: COLOR_LINE_LIGHTER,
  LINE_LIGHT: COLOR_LINE_LIGHT,
  LINE: COLOR_LINE,
  LINE_DARK: COLOR_LINE_DARK,
  LINE_DARKER: COLOR_LINE_DARKER,
  
  FILL_LIGHTER: COLOR_FILL_LIGHTER,
  FILL_LIGHT: COLOR_FILL_LIGHT,
  FILL: COLOR_FILL,
  FILL_DARK: COLOR_FILL_DARK,
  FILL_DARKER: COLOR_FILL_DARKER,
  
  SUCCESS_LIGHTER: COLOR_SUCCESS_LIGHTER,
  SUCCESS_LIGHT: COLOR_SUCCESS_LIGHT,
  SUCCESS: COLOR_SUCCESS,
  SUCCESS_DARK: COLOR_SUCCESS_DARK,
  SUCCESS_DARKER: COLOR_SUCCESS_DARKER,
  
  WARN_LIGHTER: COLOR_WARN_LIGHTER,
  WARN_LIGHT: COLOR_WARN_LIGHT,
  WARN: COLOR_WARN,
  WARN_DARK: COLOR_WARN_DARK,
  WARN_DARKER: COLOR_WARN_DARKER,
  
  ERROR_LIGHTER: COLOR_ERROR_LIGHTER,
  ERROR_LIGHT: COLOR_ERROR_LIGHT,
  ERROR: COLOR_ERROR,
  ERROR_DARK: COLOR_ERROR_DARK,
  ERROR_DARKER: COLOR_ERROR_DARKER,
  
  INFO_LIGHTER: COLOR_INFO_LIGHTER,
  INFO_LIGHT: COLOR_INFO_LIGHT,
  INFO: COLOR_INFO,
  INFO_DARK: COLOR_INFO_DARK,
  INFO_DARKER: COLOR_INFO_DARKER
};

export default COLOR;
