export const TRANSPARENT = 'transparent';
export const WHITE = '#fff';
export const BLACK = '#000';
export const INVERSE = '#fff';
export const INVERSE_BG = '#000';
export const BRAND = '#ff6a00';
export const BRAND_HOVER = '#ff6a00';
export const BRAND_ACTIVE = '#e50';
export const ACCENT = '#0064c8';
export const ACCENT_HOVER = '#0064c8';
export const ACCENT_ACTIVE = '#0050a0';
export const EMPHASIS = '#ff6a00'; // 突出说明，如「金额」、「最重要链接」等，用于 em 或未读标记,
export const DANGER = '#c80000';
export const CODE = '#39f';
export const GRAY_PRIMARY = '#333';
export const GRAY_SECONDARY = '#666';
export const GRAY_TERTIARY = '#999';
export const GRAY_DISABLED = '#c0c6cc';
export const GRAY_PRIMARY_BD = '#d1d5d9';
export const GRAY_SECONDARY_BD = '#e3e4e6';
export const GRAY_TERTIARY_BD = '#ebebeb';
export const GRAY_DISABLED_BD = '#e3e4e6';
export const GRAY_PRIMARY_BG = '#fff'; // 视觉上第一层级的背景色（用于 level1 的导航、dialog、dropdown 等）
export const GRAY_SECONDARY_BG = '#f4f6f7'; // 视觉上第二层级的背景色（用于 level2 的导航）
export const GRAY_TERTIARY_BG = '#eee'; // 视觉上第三层级的背景色（用于 body）
export const GRAY_DISABLED_BG = '#f3f4f5';
export const GRAY_SECONDARY_FADE_BG = 'rgba(0,46,70,0.04314)'; // 等价于 BG_SECONDARY
export const GRAY_TERTIARY_FADE_BG = 'rgba(0,0,0,0.066667)'; // 等价于 BG_TERTIARY
export const HELP = '#888';
export const INFO = '#0064c8';
export const SUCCESS = '#1e8e3e';
export const WARNING = '#ffc440';
export const ERROR = '#d93026';
export const HELP_TINT = '#f7f7f7';
export const INFO_TINT = '#ebf4fb';
export const SUCCESS_TINT = '#edfcf1';
export const WARNING_TINT = '#fff7db';
export const ERROR_TINT = '#fcefee';
export const HELP_TINT_FADE = 'rgba(0,0,0,0.031373)';
export const INFO_TINT_FADE = 'rgba(0,115,204,0.078431)';
export const SUCCESS_TINT_FADE = 'rgba(0,212,57,0.070588)';
export const WARNING_TINT_FADE = 'rgba(255,198,0,0.141176)';
export const ERROR_TINT_FADE = 'rgba(210,15,0,0.066667)';
export const SHADOW = 'rgba(0,0,0,0.16)';
export const BACKDROP = 'rgba(0,0,0,0.2)';
