export type {
  IErrorDiagnoseAnswer as ErrorDiagnoseAnswer,
  IErrorDiagnoseSample as ErrorDiagnoseSample
} from './common';
export type {
  IParamsErrorDiagnose as ParamsErrorDiagnose
} from './params';
export type {
  IDataErrorDiagnose as DataErrorDiagnose,
  IDataErrorDiagnoseAnswerFeedback as DataErrorDiagnoseAnswerFeedback
} from './data';
export {
  IApiDataErrorDiagnose as ApiDataErrorDiagnose,
  IApiDataErrorDiagnoseAnswerFeedback as ApiDataErrorDiagnoseAnswerFeedback,
  IApiDataErrorDiagnoseAnswerFeedbackLike as ApiDataErrorDiagnoseAnswerFeedbackLike,
  IApiDataErrorDiagnoseAnswerFeedbackLikeCancel as ApiDataErrorDiagnoseAnswerFeedbackLikeCancel,
  IApiDataErrorDiagnoseAnswerFeedbackDislike as ApiDataErrorDiagnoseAnswerFeedbackDislike,
  IApiDataErrorDiagnoseAnswerFeedbackDislikeCancel as ApiDataErrorDiagnoseAnswerFeedbackDislikeCancel
} from './api';