const TRANSPARENT = 'transparent';
const DISABLED = '#c0c6cc';
const INVERSE = '#fff';
const BRAND = '#ff6a00';
const BRAND_HOVER = '#ff6a00';
const BRAND_ACTIVE = '#e50';
const ACCENT = '#0064c8';
const ACCENT_HOVER = '#0064c8';
const ACCENT_ACTIVE = '#0050a0';
const HELP = '#888';
const INFO = '#0064c8';
const SUCCESS = '#1e8e3e';
const WARNING = '#ffc440';
const ERROR = '#d93026';
const DANGER = '#c80000';
const EMPHASIS = '#ff6a00'; // 突出说明，如「金额」、「最重要链接」等，用于 em 或未读标记,
const CODE = '#f25c7f';
const GRAY_TITLE = '#111';
const GRAY_PRIMARY = '#333';
const GRAY_SECONDARY = '#666';
const GRAY_TERTIARY = '#999';

const TEXT_DISABLED = DISABLED;
const TEXT_INVERSE = INVERSE;
const TEXT_BRAND = BRAND;
const TEXT_BRAND_HOVER = BRAND_HOVER;
const TEXT_BRAND_ACTIVE = BRAND_ACTIVE;
const TEXT_ACCENT = ACCENT;
const TEXT_ACCENT_HOVER = ACCENT_HOVER;
const TEXT_ACCENT_ACTIVE = ACCENT_ACTIVE;
const TEXT_TITLE = GRAY_TITLE;
const TEXT_PRIMARY = GRAY_PRIMARY;
const TEXT_SECONDARY = GRAY_SECONDARY;
const TEXT_TERTIARY = GRAY_TERTIARY;
const TEXT_HELP = HELP;
const TEXT_INFO = INFO;
const TEXT_SUCCESS = SUCCESS;
const TEXT_WARNING = WARNING;
const TEXT_ERROR = ERROR;
const TEXT_DANGER = DANGER;
const TEXT_EMPHASIS = EMPHASIS;

const BG_DISABLED = DISABLED;
const BG_BRAND = BRAND;
const BG_BRAND_HOVER = BRAND_HOVER;
const BG_BRAND_ACTIVE = BRAND_ACTIVE;
const BG_ACCENT = ACCENT;
const BG_ACCENT_HOVER = ACCENT_HOVER;
const BG_ACCENT_ACTIVE = ACCENT_ACTIVE;
const BG_PRIMARY = '#fff'; // 视觉上第一层级的背景色（用于 level1 的导航、dialog、dropdown 等）
const BG_SECONDARY = '#f7f9fa'; // 视觉上第二层级的背景色（用于 level2 的导航）
const BG_SECONDARY_FADE = 'rgba(0,64,96,0.03137)'; // 等价于 BG_SECONDARY
const BG_TERTIARY = '#ebebeb'; // 视觉上第三层级的背景色（用于 body）
const BG_TERTIARY_FADE = 'rgba(0,0,0,0.07843)'; // 等价于 BG_TERTIARY
const BG_HELP = '#f7f7f7';
const BG_INFO = '#ebf4fb';
const BG_SUCCESS = '#edfcf1';
const BG_WARNING = '#fff7db';
const BG_ERROR = '#fcefee';
const BG_DANGER = DANGER;

const BORDER_DISABLED = DISABLED;
const BORDER_BRAND = BRAND;
const BORDER_BRAND_HOVER = BRAND_HOVER;
const BORDER_BRAND_ACTIVE = BRAND_ACTIVE;
const BORDER_ACCENT = ACCENT;
const BORDER_ACCENT_HOVER = ACCENT_HOVER;
const BORDER_ACCENT_ACTIVE = ACCENT_ACTIVE;
const BORDER_PRIMARY = '#efefef';
const BORDER_SECONDARY = '#dedede';
const BORDER_TERTIARY = DISABLED;
const BORDER_HELP = HELP;
const BORDER_INFO = INFO;
const BORDER_SUCCESS = SUCCESS;
const BORDER_WARNING = WARNING;
const BORDER_ERROR = ERROR;
const BORDER_DANGER = DANGER;
const BORDER_INPUT = DISABLED;
const BORDER_INPUT_HOVER = BORDER_INPUT;
const BORDER_INPUT_FOCUS = BORDER_ACCENT;

const INPUT_PLACEHOLDER = GRAY_TERTIARY;
const INPUT_TEXT = GRAY_PRIMARY;
const INPUT_BG = BG_PRIMARY;
const INPUT_BORDER = BORDER_INPUT;
const INPUT_TEXT_HOVER = GRAY_PRIMARY;
const INPUT_BG_HOVER = BG_PRIMARY;
const INPUT_BORDER_HOVER = BORDER_INPUT_HOVER;
const INPUT_TEXT_FOCUS = GRAY_PRIMARY;
const INPUT_BG_FOCUS = BG_PRIMARY;
const INPUT_BORDER_FOCUS = BORDER_INPUT_FOCUS;
const INPUT_BORDER_FOCUS_BRAND = BORDER_BRAND; // 边框色变种
const INPUT_TEXT_DISABLED = DISABLED;
const INPUT_BG_DISABLED = BG_SECONDARY;
const INPUT_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 链接
 * 
 * * 一个 LINK_DISABLED
 * * LINK_XX
 *   - `LINK_PRIMARY`
 *   - `LINK_SECONDARY`
 *   - `LINK_TERTIARY` 
 *   - `LINK_BRAND` 
 *   - `LINK_BRAND_SECONDARY` 
 * * 每个 LINK_XX 会有以下变种 _VISITED / _HOVER / _ACTIVE 三个变种
 *   - `_VISITED` 对 `:visited`
 *   - `_HOVER` 对 `:hover` + `:focus`
 *   - `_ACTIVE` 对 `:active`
 */
const LINK_DISABLED = TEXT_DISABLED; // 只需要一个 disabled，不需要变种
const LINK_PRIMARY = TEXT_ACCENT;
const LINK_PRIMARY_VISITED = TEXT_ACCENT;
const LINK_PRIMARY_HOVER = TEXT_ACCENT;
const LINK_PRIMARY_ACTIVE = TEXT_ACCENT;

const LINK_SECONDARY = TEXT_SECONDARY;
const LINK_SECONDARY_VISITED = TEXT_SECONDARY;
const LINK_SECONDARY_HOVER = TEXT_ACCENT;
const LINK_SECONDARY_ACTIVE = TEXT_ACCENT;

const LINK_TERTIARY = GRAY_SECONDARY;
const LINK_TERTIARY_VISITED = GRAY_SECONDARY;
const LINK_TERTIARY_HOVER = GRAY_PRIMARY;
const LINK_TERTIARY_ACTIVE = GRAY_PRIMARY;

const LINK_BRAND = TEXT_BRAND;
const LINK_BRAND_VISITED = TEXT_BRAND;
const LINK_BRAND_HOVER = TEXT_BRAND;
const LINK_BRAND_ACTIVE = TEXT_BRAND;

const LINK_BRAND_SECONDARY = GRAY_SECONDARY;
const LINK_BRAND_SECONDARY_VISITED = GRAY_SECONDARY;
const LINK_BRAND_SECONDARY_HOVER = TEXT_BRAND;
const LINK_BRAND_SECONDARY_ACTIVE = TEXT_BRAND;

/**
 * 按钮，需要定义
 * * 文字色
 * * 背景色
 * * 边框色
 * 
 * 每种色需要定义如下状态：
 * * 正常
 * * `:hover` + `:focus`
 * * `:active`
 * * `:disabled`
 */

/**
 * 危险警告按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 白字 | 红底 | 红边
 * HOVER | 白字 | 红底 | 红边
 * ACTIVE | 白字 | 深红底 | 红边
 * 禁用 | 白字 | 灰底 | 灰边
 */
const BUTTON_DANGER_TEXT = TEXT_INVERSE;
const BUTTON_DANGER_BG = BG_DANGER;
const BUTTON_DANGER_BORDER = BORDER_DANGER;
const BUTTON_DANGER_TEXT_HOVER = TEXT_INVERSE;
const BUTTON_DANGER_BG_HOVER = BG_DANGER;
const BUTTON_DANGER_BORDER_HOVER = BORDER_DANGER;
const BUTTON_DANGER_TEXT_ACTIVE = TEXT_INVERSE;
const BUTTON_DANGER_BG_ACTIVE = BG_DANGER;
const BUTTON_DANGER_BORDER_ACTIVE = BORDER_DANGER;
const BUTTON_DANGER_TEXT_DISABLED = TEXT_INVERSE;
const BUTTON_DANGER_BG_DISABLED = BG_DISABLED;
const BUTTON_DANGER_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 菜单栏一整条的按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 透明浅灰底 | 无边
 * HOVER | 白字 | 红底 | 无边
 * ACTIVE | 白字 | 深红底 | 无边
 * 禁用 | 灰字 | 无底 | 灰边
 */
const BUTTON_MENU_TEXT = TEXT_SECONDARY;
const BUTTON_MENU_BG = TRANSPARENT;
const BUTTON_MENU_BORDER = TRANSPARENT;
const BUTTON_MENU_TEXT_HOVER = TEXT_SECONDARY;
const BUTTON_MENU_BG_HOVER = BG_SECONDARY_FADE;
const BUTTON_MENU_BORDER_HOVER = TRANSPARENT;
const BUTTON_MENU_TEXT_ACTIVE = TEXT_PRIMARY;
const BUTTON_MENU_BG_ACTIVE = BG_TERTIARY_FADE;
const BUTTON_MENU_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_MENU_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_MENU_BG_DISABLED = TRANSPARENT;
const BUTTON_MENU_BORDER_DISABLED = TRANSPARENT;

/**
 * 主按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 白字 | 蓝底 | 蓝边
 * HOVER | 白字 | 蓝底 | 蓝边
 * 禁用 | 白字 | 灰底 | 灰边
 */
const BUTTON_PRIMARY_TEXT = TEXT_INVERSE;
const BUTTON_PRIMARY_BG = BG_ACCENT;
const BUTTON_PRIMARY_BORDER = BORDER_ACCENT;
const BUTTON_PRIMARY_TEXT_HOVER = TEXT_INVERSE;
const BUTTON_PRIMARY_BG_HOVER = BG_ACCENT_HOVER;
const BUTTON_PRIMARY_BORDER_HOVER = BORDER_ACCENT_HOVER;
const BUTTON_PRIMARY_TEXT_ACTIVE = TEXT_INVERSE;
const BUTTON_PRIMARY_BG_ACTIVE = BG_ACCENT_ACTIVE;
const BUTTON_PRIMARY_BORDER_ACTIVE = BORDER_ACCENT_ACTIVE;
const BUTTON_PRIMARY_TEXT_DISABLED = TEXT_INVERSE;
const BUTTON_PRIMARY_BG_DISABLED = BG_DISABLED;
const BUTTON_PRIMARY_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 次按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 白底 | 灰边
 * HOVER | 黑字 | 浅灰底 | 灰边
 * 禁用 | 灰字 | 浅灰底 | 灰边
 */
const BUTTON_SECONDARY_TEXT = TEXT_SECONDARY;
const BUTTON_SECONDARY_BG = BG_PRIMARY;
const BUTTON_SECONDARY_BORDER = BORDER_SECONDARY;
const BUTTON_SECONDARY_TEXT_HOVER = TEXT_PRIMARY;
const BUTTON_SECONDARY_BG_HOVER = BG_SECONDARY;
const BUTTON_SECONDARY_BORDER_HOVER = BORDER_SECONDARY;
const BUTTON_SECONDARY_TEXT_ACTIVE = TEXT_PRIMARY;
const BUTTON_SECONDARY_BG_ACTIVE = BG_SECONDARY;
const BUTTON_SECONDARY_BORDER_ACTIVE = BORDER_SECONDARY;
const BUTTON_SECONDARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_SECONDARY_BG_DISABLED = BG_PRIMARY;
const BUTTON_SECONDARY_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 三级按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 无底 | 无边
 * HOVER | 黑字 | 灰底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TERTIARY_TEXT = TEXT_SECONDARY;
const BUTTON_TERTIARY_BG = TRANSPARENT;
const BUTTON_TERTIARY_BORDER = TRANSPARENT;
const BUTTON_TERTIARY_TEXT_HOVER = TEXT_PRIMARY;
const BUTTON_TERTIARY_BG_HOVER = BG_SECONDARY;
const BUTTON_TERTIARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TERTIARY_TEXT_ACTIVE = TEXT_PRIMARY;
const BUTTON_TERTIARY_BG_ACTIVE = BG_SECONDARY;
const BUTTON_TERTIARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TERTIARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TERTIARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TERTIARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 主按钮（Brand 变种）
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 白字 | 橙底 | 橙边
 * HOVER | 白字 | 橙底 | 橙边
 * 禁用 | 白字 | 灰底 | 灰边
 */
const BUTTON_BRAND_PRIMARY_TEXT = TEXT_INVERSE;
const BUTTON_BRAND_PRIMARY_BG = BG_BRAND;
const BUTTON_BRAND_PRIMARY_BORDER = BORDER_BRAND;
const BUTTON_BRAND_PRIMARY_TEXT_HOVER = TEXT_INVERSE;
const BUTTON_BRAND_PRIMARY_BG_HOVER = BG_BRAND_HOVER;
const BUTTON_BRAND_PRIMARY_BORDER_HOVER = BORDER_BRAND_HOVER;
const BUTTON_BRAND_PRIMARY_TEXT_ACTIVE = TEXT_INVERSE;
const BUTTON_BRAND_PRIMARY_BG_ACTIVE = BG_BRAND_ACTIVE;
const BUTTON_BRAND_PRIMARY_BORDER_ACTIVE = BORDER_BRAND_ACTIVE;
const BUTTON_BRAND_PRIMARY_TEXT_DISABLED = TEXT_INVERSE;
const BUTTON_BRAND_PRIMARY_BG_DISABLED = BG_DISABLED;
const BUTTON_BRAND_PRIMARY_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 次按钮（Brand 变种）
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 橙字 | 白底 | 橙边
 * HOVER | 橙字 | 白底 | 橙边
 * 禁用 | 灰字 | 浅底 | 灰边
 */
const BUTTON_BRAND_SECONDARY_TEXT = TEXT_BRAND;
const BUTTON_BRAND_SECONDARY_BG = BG_PRIMARY;
const BUTTON_BRAND_SECONDARY_BORDER = BORDER_BRAND;
const BUTTON_BRAND_SECONDARY_TEXT_HOVER = BORDER_BRAND_HOVER;
const BUTTON_BRAND_SECONDARY_BG_HOVER = BG_PRIMARY;
const BUTTON_BRAND_SECONDARY_BORDER_HOVER = BORDER_BRAND_HOVER;
const BUTTON_BRAND_SECONDARY_TEXT_ACTIVE = TEXT_BRAND_ACTIVE;
const BUTTON_BRAND_SECONDARY_BG_ACTIVE = BG_PRIMARY;
const BUTTON_BRAND_SECONDARY_BORDER_ACTIVE = BORDER_BRAND_ACTIVE;
const BUTTON_BRAND_SECONDARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_BRAND_SECONDARY_BG_DISABLED = BG_PRIMARY;
const BUTTON_BRAND_SECONDARY_BORDER_DISABLED = BORDER_DISABLED;

/**
 * 三级按钮（Brand 变种）
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 橙字 | 无底 | 无边
 * HOVER | 橙字 | 灰底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_BRAND_TERTIARY_TEXT = TEXT_BRAND;
const BUTTON_BRAND_TERTIARY_BG = TRANSPARENT;
const BUTTON_BRAND_TERTIARY_BORDER = TRANSPARENT;
const BUTTON_BRAND_TERTIARY_TEXT_HOVER = TEXT_BRAND_HOVER;
const BUTTON_BRAND_TERTIARY_BG_HOVER = BG_SECONDARY;
const BUTTON_BRAND_TERTIARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_BRAND_TERTIARY_TEXT_ACTIVE = TEXT_BRAND_ACTIVE;
const BUTTON_BRAND_TERTIARY_BG_ACTIVE = BG_SECONDARY;
const BUTTON_BRAND_TERTIARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_BRAND_TERTIARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_BRAND_TERTIARY_BG_DISABLED = TRANSPARENT;
const BUTTON_BRAND_TERTIARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 主文字按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 蓝字 | 无底 | 无边
 * HOVER | 蓝字 | 无底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TEXT_PRIMARY_TEXT = TEXT_ACCENT;
const BUTTON_TEXT_PRIMARY_BG = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_BORDER = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_TEXT_HOVER = TEXT_ACCENT_HOVER;
const BUTTON_TEXT_PRIMARY_BG_HOVER = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_TEXT_ACTIVE = TEXT_ACCENT_HOVER;
const BUTTON_TEXT_PRIMARY_BG_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TEXT_PRIMARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TEXT_PRIMARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 次文字按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 无底 | 无边
 * HOVER | 蓝字 | 无底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TEXT_SECONDARY_TEXT = TEXT_SECONDARY;
const BUTTON_TEXT_SECONDARY_BG = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_BORDER = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_TEXT_HOVER = TEXT_ACCENT;
const BUTTON_TEXT_SECONDARY_BG_HOVER = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_TEXT_ACTIVE = TEXT_ACCENT;
const BUTTON_TEXT_SECONDARY_BG_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TEXT_SECONDARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TEXT_SECONDARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 三级文字按钮
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 无底 | 无边
 * HOVER | 黑字 | 无底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TEXT_TERTIARY_TEXT = TEXT_SECONDARY;
const BUTTON_TEXT_TERTIARY_BG = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_BORDER = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_TEXT_HOVER = TEXT_PRIMARY;
const BUTTON_TEXT_TERTIARY_BG_HOVER = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_TEXT_ACTIVE = TEXT_PRIMARY;
const BUTTON_TEXT_TERTIARY_BG_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TEXT_TERTIARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TEXT_TERTIARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 主文字按钮（Brand 变种）
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 橙字 | 无底 | 无边
 * HOVER | 橙字 | 无底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TEXT_BRAND_PRIMARY_TEXT = TEXT_BRAND;
const BUTTON_TEXT_BRAND_PRIMARY_BG = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_BORDER = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_TEXT_HOVER = TEXT_BRAND_HOVER;
const BUTTON_TEXT_BRAND_PRIMARY_BG_HOVER = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_TEXT_ACTIVE = TEXT_BRAND_HOVER;
const BUTTON_TEXT_BRAND_PRIMARY_BG_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TEXT_BRAND_PRIMARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TEXT_BRAND_PRIMARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 次文字按钮（Brand 变种）
 * 
 * 态\色 | 字 | 底 | 边
 * :-- | :-- | :-- | :--
 * 正常 | 黑字 | 无底 | 无边
 * HOVER | 橙字 | 无底 | 无边
 * 禁用 | 灰字 | 无底 | 无边
 */
const BUTTON_TEXT_BRAND_SECONDARY_TEXT = TEXT_SECONDARY;
const BUTTON_TEXT_BRAND_SECONDARY_BG = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_BORDER = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_TEXT_HOVER = TEXT_BRAND;
const BUTTON_TEXT_BRAND_SECONDARY_BG_HOVER = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_BORDER_HOVER = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_TEXT_ACTIVE = TEXT_BRAND;
const BUTTON_TEXT_BRAND_SECONDARY_BG_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_BORDER_ACTIVE = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_TEXT_DISABLED = TEXT_DISABLED;
const BUTTON_TEXT_BRAND_SECONDARY_BG_DISABLED = TRANSPARENT;
const BUTTON_TEXT_BRAND_SECONDARY_BORDER_DISABLED = TRANSPARENT;

/**
 * 参考 github 的命名
 * 
 * 大的分类（前缀）
 * - `TEXT_` 前景色（文字、图标）
 * - `LINK_` 链接色
 * - `BORDER_` 边框色、线条色
 * - `BG_` 背景色、填充色
 * 
 * 每个分类必须包含：
 * 
 * - BRAND 品牌色
 * - ACCENT 强调色
 * - ACCENT_HOVER 强调色（hover 状态）
 * - ACCENT_ACTIVE 强调色（hover 状态）
 * - PRIMARY 第一级
 * - SECONDARY 第二级
 * - TERTIARY 第三级
 * - DISABLED 禁用色
 * - HELP 帮助色
 * - INFO 信息色
 * - SUCCESS 成功色
 * - WARNING 警告色
 * - ERROR 错误色
 * - DANGER 危险色
 */
export default {
  // --------------------------------------------------------------- //
  // 通用文本
  // --------------------------------------------------------------- //
  TEXT_DISABLED,
  TEXT_BRAND,
  TEXT_BRAND_HOVER,
  TEXT_BRAND_ACTIVE,
  TEXT_ACCENT,
  TEXT_ACCENT_HOVER,
  TEXT_ACCENT_ACTIVE,
  TEXT_TITLE,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_TERTIARY, // 用于说明性的文字
  TEXT_INVERSE,
  TEXT_HELP,
  TEXT_INFO,
  TEXT_SUCCESS,
  TEXT_WARNING,
  TEXT_ERROR,
  TEXT_DANGER,
  TEXT_EMPHASIS,
  TEXT_CODE: CODE,
  
  // --------------------------------------------------------------- //
  // 通用背景
  // --------------------------------------------------------------- //
  BG_DISABLED,
  BG_BRAND,
  BG_BRAND_HOVER,
  BG_BRAND_ACTIVE,
  BG_ACCENT,
  BG_ACCENT_HOVER,
  BG_ACCENT_ACTIVE,
  BG_PRIMARY,
  BG_SECONDARY,
  BG_TERTIARY,
  BG_SECONDARY_FADE,
  BG_TERTIARY_FADE,
  BG_HELP,
  BG_INFO,
  BG_SUCCESS,
  BG_WARNING,
  BG_ERROR,
  BG_DANGER,
  BG_BACKDROP: 'rgba(0, 0, 0, 0.2)',
  
  // --------------------------------------------------------------- //
  // 通用边框
  // --------------------------------------------------------------- //
  BORDER_DISABLED,
  BORDER_BRAND,
  BORDER_BRAND_HOVER,
  BORDER_BRAND_ACTIVE,
  BORDER_ACCENT,
  BORDER_ACCENT_HOVER,
  BORDER_ACCENT_ACTIVE,
  BORDER_PRIMARY,
  BORDER_SECONDARY,
  BORDER_TERTIARY,
  BORDER_HELP,
  BORDER_INFO,
  BORDER_SUCCESS,
  BORDER_WARNING,
  BORDER_ERROR,
  BORDER_DANGER,
  
  // --------------------------------------------------------------- //
  // 组件 - 输入框
  // --------------------------------------------------------------- //
  INPUT_TEXT_DISABLED,
  INPUT_BG_DISABLED,
  INPUT_BORDER_DISABLED,
  INPUT_PLACEHOLDER,
  INPUT_TEXT,
  INPUT_BG,
  INPUT_BORDER,
  INPUT_TEXT_HOVER,
  INPUT_BG_HOVER,
  INPUT_BORDER_HOVER,
  INPUT_TEXT_FOCUS,
  INPUT_BG_FOCUS,
  INPUT_BORDER_FOCUS,
  INPUT_BORDER_FOCUS_BRAND,
  
  // --------------------------------------------------------------- //
  // 组件 - 链接
  // --------------------------------------------------------------- //
  LINK_DISABLED,
  LINK_PRIMARY,
  LINK_PRIMARY_VISITED,
  LINK_PRIMARY_HOVER,
  LINK_PRIMARY_ACTIVE,
  LINK_SECONDARY,
  LINK_SECONDARY_VISITED,
  LINK_SECONDARY_HOVER,
  LINK_SECONDARY_ACTIVE,
  LINK_TERTIARY,
  LINK_TERTIARY_VISITED,
  LINK_TERTIARY_HOVER,
  LINK_TERTIARY_ACTIVE,
  LINK_BRAND,
  LINK_BRAND_VISITED,
  LINK_BRAND_HOVER,
  LINK_BRAND_ACTIVE,
  LINK_BRAND_SECONDARY,
  LINK_BRAND_SECONDARY_VISITED,
  LINK_BRAND_SECONDARY_HOVER,
  LINK_BRAND_SECONDARY_ACTIVE,
  
  // --------------------------------------------------------------- //
  // 组件 - 按钮
  // --------------------------------------------------------------- //
  BUTTON_DANGER_TEXT,
  BUTTON_DANGER_BG,
  BUTTON_DANGER_BORDER,
  BUTTON_DANGER_TEXT_HOVER,
  BUTTON_DANGER_BG_HOVER,
  BUTTON_DANGER_BORDER_HOVER,
  BUTTON_DANGER_TEXT_ACTIVE,
  BUTTON_DANGER_BG_ACTIVE,
  BUTTON_DANGER_BORDER_ACTIVE,
  BUTTON_DANGER_TEXT_DISABLED,
  BUTTON_DANGER_BG_DISABLED,
  BUTTON_DANGER_BORDER_DISABLED,
  BUTTON_MENU_TEXT,
  BUTTON_MENU_BG,
  BUTTON_MENU_BORDER,
  BUTTON_MENU_TEXT_HOVER,
  BUTTON_MENU_BG_HOVER,
  BUTTON_MENU_BORDER_HOVER,
  BUTTON_MENU_TEXT_ACTIVE,
  BUTTON_MENU_BG_ACTIVE,
  BUTTON_MENU_BORDER_ACTIVE,
  BUTTON_MENU_TEXT_DISABLED,
  BUTTON_MENU_BG_DISABLED,
  BUTTON_MENU_BORDER_DISABLED,
  BUTTON_PRIMARY_TEXT,
  BUTTON_PRIMARY_BG,
  BUTTON_PRIMARY_BORDER,
  BUTTON_PRIMARY_TEXT_HOVER,
  BUTTON_PRIMARY_BG_HOVER,
  BUTTON_PRIMARY_BORDER_HOVER,
  BUTTON_PRIMARY_TEXT_ACTIVE,
  BUTTON_PRIMARY_BG_ACTIVE,
  BUTTON_PRIMARY_BORDER_ACTIVE,
  BUTTON_PRIMARY_TEXT_DISABLED,
  BUTTON_PRIMARY_BG_DISABLED,
  BUTTON_PRIMARY_BORDER_DISABLED,
  BUTTON_SECONDARY_TEXT,
  BUTTON_SECONDARY_BG,
  BUTTON_SECONDARY_BORDER,
  BUTTON_SECONDARY_TEXT_HOVER,
  BUTTON_SECONDARY_BG_HOVER,
  BUTTON_SECONDARY_BORDER_HOVER,
  BUTTON_SECONDARY_TEXT_ACTIVE,
  BUTTON_SECONDARY_BG_ACTIVE,
  BUTTON_SECONDARY_BORDER_ACTIVE,
  BUTTON_SECONDARY_TEXT_DISABLED,
  BUTTON_SECONDARY_BG_DISABLED,
  BUTTON_SECONDARY_BORDER_DISABLED,
  BUTTON_TERTIARY_TEXT,
  BUTTON_TERTIARY_BG,
  BUTTON_TERTIARY_BORDER,
  BUTTON_TERTIARY_TEXT_HOVER,
  BUTTON_TERTIARY_BG_HOVER,
  BUTTON_TERTIARY_BORDER_HOVER,
  BUTTON_TERTIARY_TEXT_ACTIVE,
  BUTTON_TERTIARY_BG_ACTIVE,
  BUTTON_TERTIARY_BORDER_ACTIVE,
  BUTTON_TERTIARY_TEXT_DISABLED,
  BUTTON_TERTIARY_BG_DISABLED,
  BUTTON_TERTIARY_BORDER_DISABLED,
  BUTTON_BRAND_PRIMARY_TEXT,
  BUTTON_BRAND_PRIMARY_BG,
  BUTTON_BRAND_PRIMARY_BORDER,
  BUTTON_BRAND_PRIMARY_TEXT_HOVER,
  BUTTON_BRAND_PRIMARY_BG_HOVER,
  BUTTON_BRAND_PRIMARY_BORDER_HOVER,
  BUTTON_BRAND_PRIMARY_TEXT_ACTIVE,
  BUTTON_BRAND_PRIMARY_BG_ACTIVE,
  BUTTON_BRAND_PRIMARY_BORDER_ACTIVE,
  BUTTON_BRAND_PRIMARY_TEXT_DISABLED,
  BUTTON_BRAND_PRIMARY_BG_DISABLED,
  BUTTON_BRAND_PRIMARY_BORDER_DISABLED,
  BUTTON_BRAND_SECONDARY_TEXT,
  BUTTON_BRAND_SECONDARY_BG,
  BUTTON_BRAND_SECONDARY_BORDER,
  BUTTON_BRAND_SECONDARY_TEXT_HOVER,
  BUTTON_BRAND_SECONDARY_BG_HOVER,
  BUTTON_BRAND_SECONDARY_BORDER_HOVER,
  BUTTON_BRAND_SECONDARY_TEXT_ACTIVE,
  BUTTON_BRAND_SECONDARY_BG_ACTIVE,
  BUTTON_BRAND_SECONDARY_BORDER_ACTIVE,
  BUTTON_BRAND_SECONDARY_TEXT_DISABLED,
  BUTTON_BRAND_SECONDARY_BG_DISABLED,
  BUTTON_BRAND_SECONDARY_BORDER_DISABLED,
  BUTTON_BRAND_TERTIARY_TEXT,
  BUTTON_BRAND_TERTIARY_BG,
  BUTTON_BRAND_TERTIARY_BORDER,
  BUTTON_BRAND_TERTIARY_TEXT_HOVER,
  BUTTON_BRAND_TERTIARY_BG_HOVER,
  BUTTON_BRAND_TERTIARY_BORDER_HOVER,
  BUTTON_BRAND_TERTIARY_TEXT_ACTIVE,
  BUTTON_BRAND_TERTIARY_BG_ACTIVE,
  BUTTON_BRAND_TERTIARY_BORDER_ACTIVE,
  BUTTON_BRAND_TERTIARY_TEXT_DISABLED,
  BUTTON_BRAND_TERTIARY_BG_DISABLED,
  BUTTON_BRAND_TERTIARY_BORDER_DISABLED,
  BUTTON_TEXT_PRIMARY_TEXT,
  BUTTON_TEXT_PRIMARY_BG,
  BUTTON_TEXT_PRIMARY_BORDER,
  BUTTON_TEXT_PRIMARY_TEXT_HOVER,
  BUTTON_TEXT_PRIMARY_BG_HOVER,
  BUTTON_TEXT_PRIMARY_BORDER_HOVER,
  BUTTON_TEXT_PRIMARY_TEXT_ACTIVE,
  BUTTON_TEXT_PRIMARY_BG_ACTIVE,
  BUTTON_TEXT_PRIMARY_BORDER_ACTIVE,
  BUTTON_TEXT_PRIMARY_TEXT_DISABLED,
  BUTTON_TEXT_PRIMARY_BG_DISABLED,
  BUTTON_TEXT_PRIMARY_BORDER_DISABLED,
  BUTTON_TEXT_SECONDARY_TEXT,
  BUTTON_TEXT_SECONDARY_BG,
  BUTTON_TEXT_SECONDARY_BORDER,
  BUTTON_TEXT_SECONDARY_TEXT_HOVER,
  BUTTON_TEXT_SECONDARY_BG_HOVER,
  BUTTON_TEXT_SECONDARY_BORDER_HOVER,
  BUTTON_TEXT_SECONDARY_TEXT_ACTIVE,
  BUTTON_TEXT_SECONDARY_BG_ACTIVE,
  BUTTON_TEXT_SECONDARY_BORDER_ACTIVE,
  BUTTON_TEXT_SECONDARY_TEXT_DISABLED,
  BUTTON_TEXT_SECONDARY_BG_DISABLED,
  BUTTON_TEXT_SECONDARY_BORDER_DISABLED,
  BUTTON_TEXT_TERTIARY_TEXT,
  BUTTON_TEXT_TERTIARY_BG,
  BUTTON_TEXT_TERTIARY_BORDER,
  BUTTON_TEXT_TERTIARY_TEXT_HOVER,
  BUTTON_TEXT_TERTIARY_BG_HOVER,
  BUTTON_TEXT_TERTIARY_BORDER_HOVER,
  BUTTON_TEXT_TERTIARY_TEXT_ACTIVE,
  BUTTON_TEXT_TERTIARY_BG_ACTIVE,
  BUTTON_TEXT_TERTIARY_BORDER_ACTIVE,
  BUTTON_TEXT_TERTIARY_TEXT_DISABLED,
  BUTTON_TEXT_TERTIARY_BG_DISABLED,
  BUTTON_TEXT_TERTIARY_BORDER_DISABLED,
  BUTTON_TEXT_BRAND_PRIMARY_TEXT,
  BUTTON_TEXT_BRAND_PRIMARY_BG,
  BUTTON_TEXT_BRAND_PRIMARY_BORDER,
  BUTTON_TEXT_BRAND_PRIMARY_TEXT_HOVER,
  BUTTON_TEXT_BRAND_PRIMARY_BG_HOVER,
  BUTTON_TEXT_BRAND_PRIMARY_BORDER_HOVER,
  BUTTON_TEXT_BRAND_PRIMARY_TEXT_ACTIVE,
  BUTTON_TEXT_BRAND_PRIMARY_BG_ACTIVE,
  BUTTON_TEXT_BRAND_PRIMARY_BORDER_ACTIVE,
  BUTTON_TEXT_BRAND_PRIMARY_TEXT_DISABLED,
  BUTTON_TEXT_BRAND_PRIMARY_BG_DISABLED,
  BUTTON_TEXT_BRAND_PRIMARY_BORDER_DISABLED,
  BUTTON_TEXT_BRAND_SECONDARY_TEXT,
  BUTTON_TEXT_BRAND_SECONDARY_BG,
  BUTTON_TEXT_BRAND_SECONDARY_BORDER,
  BUTTON_TEXT_BRAND_SECONDARY_TEXT_HOVER,
  BUTTON_TEXT_BRAND_SECONDARY_BG_HOVER,
  BUTTON_TEXT_BRAND_SECONDARY_BORDER_HOVER,
  BUTTON_TEXT_BRAND_SECONDARY_TEXT_ACTIVE,
  BUTTON_TEXT_BRAND_SECONDARY_BG_ACTIVE,
  BUTTON_TEXT_BRAND_SECONDARY_BORDER_ACTIVE,
  BUTTON_TEXT_BRAND_SECONDARY_TEXT_DISABLED,
  BUTTON_TEXT_BRAND_SECONDARY_BG_DISABLED,
  BUTTON_TEXT_BRAND_SECONDARY_BORDER_DISABLED,
  
  // --------------------------------------------------------------- //
  // TODO 杀以下
  // --------------------------------------------------------------- //
  // BRAND_ALIYUN: '#ff6a00', // TODO remove
  // TEXT_WARN: '#ffc440', // TODO remove
  // TEXT_CAPTION: '#888', // TODO remove
  // LINE_BRAND: TEXT_BRAND, // TODO remove
  // LINE_DIVIDER: '#efefef', // 浅色分割线 TODO LINE_LIGHT
  // LINE_DIVIDER_FADE: 'rgba(0,0,0,0.0627)',
  // LINE_BORDER: '#dedede', // 组件边框 TODO LINE
  // LINE_BORDER_FADE: 'rgba(0,0,0,0.1294)',
  // LINE_BORDER_HOVER: '#c0c6cc', // 深色分割线、组件边框 Hover 效果 TODO LINE_DARK
  // FILL_BRAND: TEXT_BRAND,
  // FILL_ACCENT: TEXT_ACCENT,
  // FILL_LIGHT: '#f7f9fa', // 白底 hover
  // FILL_LIGHT_FADE: 'rgba(0,64,96,0.03137)',
  // FILL_DARK: '#ebebeb',
  // FILL_DARKER: '#dedede',
  // FILL_SUCCESS: '#edfcf1',
  // FILL_NAV_LEVEL1: '#f5f5f5', // 二级导航（应用侧边栏）TODO FILL
  // FILL_NAV_LEVEL2: '#f5f5f5', // 二级导航（应用侧边栏）TODO FILL
  // FILL_TABLE_TH: '#f5f5f5',
  // FILL_TABLE_TD: '#fff',
  // FILL_DIALOG: '#fff',
  // FILL_DIALOG_HEADER: '#fff',
  // FILL_DIALOG_FOOTER: '#fff',
  // FILL_DIALOG_BACKDROP_FADE: 'rgba(0, 0, 0, 0.2)',
  // FILL_INPUT: '#fff',
  // FILL_INPUT_DISABLED: '#f7f9fa',
  // FILL_DROPDOWN: '#fff'
};
