import {
  COLORS_LIGHT,
  COLORS_DARK
} from '../color-base';

export const COLOR_FORM_CONTROL = {
  FGC: COLORS_LIGHT.GRAY_PRIMARY,
  FGC_DISABLED: COLORS_LIGHT.GRAY_DISABLED,
  BDC: COLORS_LIGHT.GRAY_TERTIARY_BD,
  BDC_HOVER: COLORS_LIGHT.GRAY_SECONDARY_BD,
  BDC_ACTIVE: COLORS_LIGHT.GRAY_PRIMARY_BD,
  BDC_FOCUS: '#66c',
  BDC_DISABLED: COLORS_LIGHT.GRAY_DISABLED_BD,
  BGC: COLORS_LIGHT.GRAY_PRIMARY_BG,
  BGC_HOVER: COLORS_LIGHT.GRAY_SECONDARY_BG,
  BGC_ACTIVE: COLORS_LIGHT.GRAY_TERTIARY_BG,
  BGC_DISABLED: COLORS_LIGHT.GRAY_DISABLED_BG
};

export const COLOR_FORM_CONTROL_DARK = {
  FGC: COLORS_DARK.GRAY_PRIMARY,
  FGC_DISABLED: COLORS_DARK.GRAY_DISABLED,
  BDC: COLORS_DARK.GRAY_TERTIARY_BD,
  BDC_HOVER: COLORS_DARK.GRAY_SECONDARY_BD,
  BDC_ACTIVE: COLORS_DARK.GRAY_PRIMARY_BD,
  BDC_FOCUS: '#66c',
  BDC_DISABLED: COLORS_DARK.GRAY_DISABLED_BD,
  BGC: COLORS_DARK.GRAY_PRIMARY_BG,
  BGC_HOVER: COLORS_DARK.GRAY_SECONDARY_BG,
  BGC_ACTIVE: COLORS_DARK.GRAY_TERTIARY_BG,
  BGC_DISABLED: COLORS_DARK.GRAY_DISABLED_BG
};
