import {
  COLORS_LIGHT,
  COLORS_DARK
} from '../color-base';

export const COLOR_TABLE = {
  BGC_TH: COLORS_LIGHT.GRAY_SECONDARY_BG,
  BGC_TD: COLORS_LIGHT.GRAY_PRIMARY_BG,
  BDC: COLORS_LIGHT.GRAY_TERTIARY_BD
};

export const COLOR_TABLE_DARK = {
  BGC_TH: COLORS_DARK.GRAY_SECONDARY_BG,
  BGC_TD: COLORS_DARK.GRAY_PRIMARY_BG,
  BDC: COLORS_DARK.GRAY_TERTIARY_BD
};
