import {
  IColorEssential,
  IColorBg
} from '../types';

export default function createConstColorBaseBg(E: IColorEssential): IColorBg {
  return {
    BG_TRANSPARENT: E.TRANSPARENT,
    BG_WHITE: E.WHITE,
    BG_BRAND: E.BRAND,
    BG_BRAND_HOVER: E.BRAND_HOVER,
    BG_BRAND_ACTIVE: E.BRAND_ACTIVE,
    BG_ACCENT: E.ACCENT,
    BG_ACCENT_HOVER: E.ACCENT_HOVER,
    BG_ACCENT_ACTIVE: E.ACCENT_ACTIVE,
    BG_PRIMARY: E.GRAY_BG_PRIMARY,
    BG_SECONDARY: E.GRAY_BG_SECONDARY,
    BG_SECONDARY_FADE: E.GRAY_BG_SECONDARY_FADE,
    BG_TERTIARY: E.GRAY_BG_TERTIARY,
    BG_TERTIARY_FADE: E.GRAY_BG_TERTIARY_FADE,
    BG_DISABLED: E.GRAY_DISABLED,
    BG_HELP: E.HELP_BG,
    BG_HELP_FADE: E.HELP_BG_FADE,
    BG_INFO: E.INFO_BG,
    BG_INFO_FADE: E.INFO_BG_FADE,
    BG_SUCCESS: E.SUCCESS_BG,
    BG_SUCCESS_FADE: E.SUCCESS_BG_FADE,
    BG_WARNING: E.WARNING_BG,
    BG_WARNING_FADE: E.WARNING_BG_FADE,
    BG_ERROR: E.ERROR_BG,
    BG_ERROR_FADE: E.ERROR_BG_FADE,
    BG_DANGER: E.DANGER,
    BG_BACKDROP: E.BACKDROP
  };
}
