export type {
  IErrorDiagnosisSolution as ErrorDiagnosisSolution,
  IErrorDiagnosisSample as ErrorDiagnosisSample
} from './common';
export type {
  IParamsErrorDiagnosis as ParamsErrorDiagnosis
} from './params';
export type {
  IDataErrorDiagnosis as DataErrorDiagnosis,
  IDataErrorDiagnosisSolutionFeedback as DataErrorDiagnosisSolutionFeedback
} from './data';
export type {
  IApiDataErrorDiagnosis as ApiDataErrorDiagnosis,
  IApiDataErrorDiagnosisSolutionFeedback as ApiDataErrorDiagnosisSolutionFeedback,
  IApiDataErrorDiagnosisSolutionFeedbackLike as ApiDataErrorDiagnosisSolutionFeedbackLike,
  IApiDataErrorDiagnosisSolutionFeedbackLikeCancel as ApiDataErrorDiagnosisSolutionFeedbackLikeCancel,
  IApiDataErrorDiagnosisSolutionFeedbackDislike as ApiDataErrorDiagnosisSolutionFeedbackDislike,
  IApiDataErrorDiagnosisSolutionFeedbackDislikeCancel as ApiDataErrorDiagnosisSolutionFeedbackDislikeCancel
} from './api';